### ISSUE TITLE
Change signature of `Plugin::create_refund( $transaction_id, $gateway, Money $amount, $description = null )`?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#131]
If, for example, an invoice number can also be entered towards the gateway in addition to a description, the current signature is not very flexible. Maybe we should consider putting all the necessary information in a transaction object:

```php
$refund = new Transaction( ... );

Plugin::create_refund( Refund $refund );
```

**Comment by rvdsteege** [comment]
We can do that, if need arises.

We're already adding meta data when creating a refund at Mollie, using the transaction ID to retrieve the data:

https://github.com/wp-pay-gateways/mollie/blob/d58e58f1d0d748f33baa5486f9741f47a2a64c77/src/Gateway.php#L850-L863

**Comment by rvdsteege** [comment]
The minimum we need for any refund are:

1. a reference to the original transaction at the gateway to (partially) refund
2. gateway (like the reference, we can not derive this from a `$payment` as the payment could have been removed within WordPress)
3. the amount to refund.

So these should be in the `Refund` constructor. Parameters like a credit invoice number, reason/description can then be set optionally. What is a `Transaction` object, does it extend another class?

@remcotolsma from https://github.com/wp-pay/core/issues/50#issuecomment-860447795:

> There must be a way to also pass on a partial amount or a credit invoice number, etc.

I don't think it matter for a `Refund` if the passed amount results in a partial or full refund? One refund amount should be sufficient or is there a reason you want to specify this?

**Comment by remcotolsma** [comment]
> What is a `Transaction` object, does it extend another class?

In the [internal Basecamp to-do "Voorstel database structuur custom tables Pronamic Pay"](https://basecamp.com/1810084/projects/10966871/todos/418984750) we are working on custom database tables setup:

![db](https://user-images.githubusercontent.com/869674/122736052-e6cff500-d27f-11eb-8dd5-a74b7be0f20a.png)

In this setup we currently have one table `wp_pronamic_pay_transactions` in which payments and refunds can be stored.

Maybe we can include the similarities between a normal payment and a refund in a Transaction class?

```
class Transaction {
    $amount;

    $transaction_id;
}

class Payment extends Transaction {

}

class Refund extends Transaction {
    $payment;
}
```

> 2. gateway (like the reference, we can not derive this from a $payment as the payment could have been removed within WordPress)

If the payment is removed within WordPress i don't think we need to support refunds anymore for that payment, a reference to `$payment` should be required.

> I don't think it matter for a `Refund` if the passed amount results in a partial or full refund? One refund amount should be sufficient or is there a reason you want to specify this?

Yes.

**Comment by rvdsteege** [comment]
Maybe refactor `PaymentInfo` class to `Transaction`, overlaps a lot.

**Comment by remcotolsma** [comment]
Currently a `Subscription` also extends the `PaymentInfo` class, a subscription is not directly a financial transaction, but a subscription does contain payment information.

But for now let's focus on the `Refund` object and set it up as minimal as possible:

```php
$refund = new Refund( $payment, $amount );

$refund->set_description( 'Test' );

Plugin::create_refund( $refund );
```

**Comment by rvdsteege** [comment]
If we require the original payment, what should we do for example when a refund is made for a WooCommerce order of which the original payment has been deleted? In WooCommerce refund support is determined per gateway and we can not disable the refunds interface for a specific order.

A user would make a refund and then get an error message about the original payment not being available, even though we don't really require the payment but only the transaction ID (which is stored in the WooCommerce order)?

**Comment by remcotolsma** [comment]
Yes, error message is ok, or create a new (in memory) `Payment` object from the WooCommerce order:
https://github.com/wp-pay-extensions/woocommerce/blob/877aee9421957caa2f63314ea6b681cf81295206/src/Gateway.php#L357-L665

But i think it's ok for now to require the original payment, but when removing a payment, this is something for users to take into account.

**Comment by rvdsteege** [comment]
Creating the in memory `Payment` sounds as a viable alternative (if the original payment is not available anymore). I'll work on this.

**Comment by remcotolsma** [comment]
We changed the signature to: `create_refund( Refund $refund )`.
