### ISSUE TITLE
Style Pronamic Pay redirect page

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#133]
On behalf of customer:

> How can I style the Pronamic pay redirect page? Adyen, my payment provider, has css classes and you use them along with your own on that page. How do I get my stylesheet loaded on that page?

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1522453114/22112?folderId=1425713

**Comment by remcotolsma** [comment]
We have the following in place:

https://github.com/pronamic/wp-pronamic-pay/blob/0ba24e2ff1213f6936c00869ec4abd8ebdd3d796/views/redirect-via-html.php#L24

We also use this in the Adyen library:

https://github.com/wp-pay-gateways/adyen/search?q=pronamic-pay-redirect

Can this be used by customers to load their own stylesheet?

https://github.com/pronamic/wp-pronamic-pay/wiki

**Comment by rvdsteege** [comment]
The `pronamic_pay_adyen_checkout_head` action can be used to print custom styles.

- https://github.com/wp-pay-gateways/adyen/search?q=pronamic_pay_adyen_checkout_head
- https://github.com/wp-pay-gateways/adyen/blob/1.3.1/src/DropInGateway.php#L296-L318

**Comment by remcotolsma** [comment]
A good catch, we even have an example: https://github.com/wp-pay-gateways/adyen#pronamic_pay_adyen_checkout_head. 

```php
add_action( 'pronamic_pay_adyen_checkout_head', 'custom_adyen_checkout_head', 15 );

function custom_adyen_checkout_head() {
	wp_register_style(
		'custom-adyen-checkout-style',
		get_stylesheet_directory_uri() . '/css/adyen-checkout.css',
		array(),
		'1.0.0'
	);

	wp_print_styles( 'custom-adyen-checkout-style' );
}
```

Need to do some work to make this action appear on the https://github.com/wp-pay-gateways/adyen/blob/1.3.1/docs/hooks.md page.

**Comment by remcotolsma** [comment]
Fixed in https://github.com/wp-pay-gateways/adyen/commit/5840cf624dbce9099e11d066b828a490d9ef6d15.
