### ISSUE TITLE
Back/abort link Pronamic Pay redirect page

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#134]
On behalf of customer:

> There isn't a back/abort link on the Pronamic pay redirect page, can I add that?

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1522453114/22112?folderId=1425713

**Comment by remcotolsma** [comment]
Is this question related to one of the following views?

- https://github.com/wp-pay-gateways/adyen/blob/4e3c988284eb11529fb678882fb56ba160832226/views/checkout-drop-in.php
- https://github.com/wp-pay-gateways/adyen/blob/4e3c988284eb11529fb678882fb56ba160832226/views/checkout-web-sdk.php

Or to:

- https://github.com/pronamic/wp-pronamic-pay/blob/0ba24e2ff1213f6936c00869ec4abd8ebdd3d796/views/redirect-via-html.php

In the Adyen library we could introduce a new action:

```php
do_action( 'pronamic_pay_adyen_checkout_footer' );
```

Which gives developers the ability to add elements to the end of the page (footer).

We could also add a back/abort link by default, maybe it is useful for all users?

**Comment by rvdsteege** [comment]
It is related to the Adyen views.

> We could also add a back/abort link by default, maybe it is useful for all users?

Should the payment then be cancelled? Otherwise, why not use the back button of the browser instead?

**Comment by remcotolsma** [comment]
I think many payment providers also offer back/abort link on their payment pages. I don't think this always results in a canceled payment. I'm also in favor of using the browser's back button, good read: https://ux.stackexchange.com/questions/74311/should-a-web-based-ui-rely-on-the-browser-back-button. Maybe ask the customer what problem he/she wants to solve with this back/abort link?

**Comment by rvdsteege** [comment]
I'm reluctant to add a `pronamic_pay_adyen_checkout_footer` action for this single purpose, as this can already be accomplished with the `pronamic_pay_adyen_checkout_head` action.

```
add_action(
	'pronamic_pay_adyen_checkout_head',
	function() {
		add_action( 'wp_print_scripts', 'pronamic_pay_adyen_checkout_footer' );
	},
	15
);

function pronamic_pay_adyen_checkout_footer() {
​    // Your code here...
}
```

I've asked for additional details from customer about the need/expected behaviour of a back/abort button.

**Comment by remcotolsma** [comment]
That feels a bit like an abuse of the `wp_print_scripts` action, as it seems to be aimed to print scripts:

> Prints scripts in document head that are in the $handles queue.

https://developer.wordpress.org/reference/functions/wp_print_scripts/

Let's wait for a response from the customer.

**Comment by rvdsteege** [comment]
The PayPal abort/cancel link cancels a payment:
- https://github.com/wp-pay-gateways/paypal/commit/56852cc9d54d20b38f13cecc4fbcde0bd09f9842
