### ISSUE TITLE
Translate Pronamic Pay redirect page

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#135]
On behalf of customer:

> The language on the Pronamic pay redirect page, how do I set it to be in Swedish?

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1522453114/22112?folderId=1425713

**Comment by remcotolsma** [comment]
Is this question related to one of the following views?

- https://github.com/wp-pay-gateways/adyen/blob/4e3c988284eb11529fb678882fb56ba160832226/views/checkout-drop-in.php
- https://github.com/wp-pay-gateways/adyen/blob/4e3c988284eb11529fb678882fb56ba160832226/views/checkout-web-sdk.php

Or to:

- https://github.com/pronamic/wp-pronamic-pay/blob/0ba24e2ff1213f6936c00869ec4abd8ebdd3d796/views/redirect-via-html.php

You can translate via https://translate.wordpress.org/locale/sv/default/wp-plugins/pronamic-ideal/, but unfortunately not all texts to be translated are currently there. Probably because many translatable texts are currently in the `vendor` folder and https://translate.wordpress.org/ does not include them.

The WP-CLI `wp i18n make-pot` command excludes the `vendor` folder by default:

> The following files and folders are always excluded: node_modules, .git, .svn, .CVS, .hg, vendor, *.min.js.

https://github.com/wp-cli/i18n-command/blob/606bbaba4471021f5404a8a78f495808c00535da/src/MakePotCommand.php#L41-L44

Another disadvantage of translating via https://translate.wordpress.org/ is that you need to translate 90% of the project to get a language pack generated:

> Once a plugin or theme translation reaches 90% of the strings from the code translated and approved in translate.wordpress.org, a language pack for the plugin and target language will be generated.

https://make.wordpress.org/meta/handbook/documentation/translations/

That goes a bit far to only translate the redirect page.

If a user can provide the translations, we may be able to include them in the plugin as well.
https://github.com/pronamic/wp-pronamic-pay/tree/develop/languages

Or the user could add custom translation file in `wp-content/languages/plugins/pronamic-ideal-sv.mo`.

**Comment by rvdsteege** [comment]
Related to the Adyen views.

I've translated the payment info section on the Adyen checkout page to place in `wp-content/languages/plugins/`. Suggested to update the translation, so we can include it with future releases.

- [pronamic_ideal-sv_SE.zip](https://github.com/pronamic/wp-pronamic-pay/files/6629630/pronamic_ideal-sv_SE.zip)
