### ISSUE TITLE
Can Adyen integration handle 3DS auth?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#141]
On behalf of customer:

> I have a question, Pronamic Adyen integration can handle 3DS auth?

- https://docs.adyen.com/online-payments/3d-secure
- https://en.wikipedia.org/wiki/3-D_Secure

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1544839903/22219?folderId=1425710

**Comment by rvdsteege** [comment]
Payments which require 3DS authentication are redirected to te verification page of the card issuer.

Test cards for 3D secure authentication:
- https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication

![b6JeS7Hkv2](https://user-images.githubusercontent.com/10371164/122352247-3ac09e00-cf4f-11eb-8854-6a187268f7f0.gif)
