### ISSUE TITLE
Convert `pronamic/wp-money` money value from `float` to `string`

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#142]
I discovered amounts with many decimal places on pronamic.eu:

```json
"unit_price":{"value":847.5800000000000409272615797817707061767578125,"currency":"EUR"},"total_amount":{"value":847.5800000000000409272615797817707061767578125,"currency":"EUR"}
```

```json
"unit_price":{"value":847.5800000000000409272615797817707061767578125,"currency":"EUR"},"total_amount":{"value":847.5800000000000409272615797817707061767578125,"currency":"EUR"}
```

Also for more recent payments created in May or June.

```
SELECT * FROM `wp_2_posts` WHERE `post_type` = 'pronamic_payment' ORDER BY `post_date` DESC LIMIT 50
```

Somehow the processing in https://github.com/pronamic/wp-money is not always very nice.

My colleague @rvdsteege already tried to reproduce the problem:

> Ik kan het lokaal met geen mogelijkheid reproduceren.
> 
> Geprobeerd/gecontroleerd:
> 
> - site taal EN vs NL;
> - Easy Digital Downloads versie;
> - bedragen in Easy Digital Downloads exclusief btw opgeven;
> - in WordPress Money de PHP i.p.v. BC Math calculator gebruiken;
> - prijs in **edd_variable_prices** meta van download (zowel lokaal als op pronamic.eu een string "49.00");
> - uitkomt van "59.29 / 1" in verschillende PHP-versies gecontroleerd met 3v4l.org (n.a.v. regeltje https://github.com/wp-pay-extensions/easy-digital-downloads/blob/2.1.2/src/Gateway.php#L513 — uitkomt was met alle versies 59.29);
> - php.ini **precision** (zowel lokaal als op pronamic.eu is dat `14`).

Strange, but as far as I'm concerned we are following the advice of https://github.com/moneyphp/money:

> In short: You shouldn't represent monetary values by a float.

Also the PHP BC Math function require strings.

https://www.php.net/manual/en/book.bc.php

```php
<?php

$test = 847.5800000000000409272615797817707061767578125;

var_dump( $test );
```

![3v4l org_L54No](https://user-images.githubusercontent.com/869674/122221991-1ebaef00-ceb2-11eb-8ee8-d372ad199803.png)

https://3v4l.org/L54No#v730

Since PHP 8, I think there have also been some developments regarding numeric strings:

- https://www.php.net/manual/en/language.types.numeric-strings.php
- https://wiki.php.net/rfc/saner-numeric-strings

We will certainly sometimes get `integer` or `float` values from extensions and gateways, but at that moment they are easy to convert to a `string`. From that moment on it is no problem at all to continue calculating with numeric strings and to store these numeric strings.

I started developing in https://github.com/pronamic/wp-number, the https://github.com/pronamic/wp-money library can use the https://github.com/pronamic/wp-number library.

_Internal Basecmp to-do:_ https://basecamp.com/1810084/projects/10966871/todos/421412045

**Comment by rvdsteege** [comment]
Should we plan this for the 6.9 milestone or after improved test coverage? I predict a lot of smaller otherwise unnoticed issues with such a seemingly small type change from `float` to `string`.

**Comment by remcotolsma** [comment]
I don't expect a lot of issues, let's try to get this in `6.9`.

**Comment by rvdsteege** [comment]
I've fixed all issues related to the removal of the `Money->get_cents()` method. That method is not used anymore in our code now.
