### ISSUE TITLE
Launch PayPal Add-On

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#144]
I think the https://github.com/wp-pay-gateways/paypal library is almost ready for launch.

**Comment by rvdsteege** [comment]
What does 'almost' mean? Any known issues or things to consider, or just awaiting #147?

**Comment by remcotolsma** [comment]
Currently only payments towards the sandbox environment are possible 🤡:

https://github.com/wp-pay-gateways/paypal/blob/cf7de680fcb43562c024fa906f137761536c6475/src/Gateway.php#L82-L88

And if payment lines are available we could use these:

https://github.com/wp-pay-gateways/paypal/blob/cf7de680fcb43562c024fa906f137761536c6475/src/Gateway.php#L121-L127

We have to take into account the following:

> **Note:** PayPal recommends passing no more than 25 items in a single button or Cart Upload command.

If there are more than 25 items we could throw an exception or or group the additional items into a final item.

and awaiting #147...

**Comment by remcotolsma** [comment]
> Currently only payments towards the sandbox environment are possible 🤡:

Fixed in https://github.com/wp-pay-gateways/paypal/commit/168263828acfd1fcfc068474af03a9fefaf52397.

> And if payment lines are available we could use these:

Fixed in https://github.com/wp-pay-gateways/paypal/commit/1a97ea3297500a4fb2b32afc3ea8d397d50469b5, for now no check on the 25 items.
