### ISSUE TITLE
Extend PayPal support in gateways

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#145]
Is the PayPal payment method supported in all the gateways?

- [ ] https://github.com/wp-pay-gateways/adyen
- [x] https://github.com/wp-pay-gateways/buckaroo
- [x] https://github.com/wp-pay-gateways/digiwallet
- [x] https://github.com/wp-pay-gateways/ems-e-commerce
- [x] https://github.com/wp-pay-gateways/icepay
- [x] https://github.com/wp-pay-gateways/ideal
- [x] https://github.com/wp-pay-gateways/ideal-advanced-v3
- [x] https://github.com/wp-pay-gateways/ideal-basic
- [x] https://github.com/wp-pay-gateways/ing-kassa-compleet
- [x] https://github.com/wp-pay-gateways/mollie
- [x] https://github.com/wp-pay-gateways/multisafepay
- [x] https://github.com/wp-pay-gateways/ogone
- [x] https://github.com/wp-pay-gateways/omnikassa-2
- [x] https://github.com/wp-pay-gateways/pay-nl
- [x] https://github.com/wp-pay-gateways/payvision
- [x] https://github.com/wp-pay-gateways/sisow
- [x] https://github.com/wp-pay-gateways/targetpay

_Internal Basecamp to-do:_ https://basecamp.com/1810084/projects/10966871/todos/335230949

**Comment by remcotolsma** [comment]
Just checked https://github.com/wp-pay-gateways/omnikassa-2/blob/master/src/PaymentBrands.php#L103, looks like this is working.

<img width="1172" alt="Schermafbeelding 2021-06-17 om 15 37 57" src="https://user-images.githubusercontent.com/869674/122407754-28ac2300-cf82-11eb-9603-7bd3e7649bfc.png">

**Comment by remcotolsma** [comment]
Just checked https://github.com/wp-pay-gateways/buckaroo/blob/master/src/Gateway.php#L354-L365, looks like this is working.

According to https://dev.buckaroo.nl/PaymentMethods/Description/paypal#pay there are no input is required for the PayPal pay action.

**Comment by remcotolsma** [comment]
The following gateways are iDEAL only gateways:

- https://github.com/wp-pay-gateways/ideal
- https://github.com/wp-pay-gateways/ideal-advanced-v3
- https://github.com/wp-pay-gateways/ideal-basic

**Comment by remcotolsma** [comment]
I just tested https://github.com/wp-pay-gateways/sisow, at first I got the following error message:

> TA6121: No PayPal API data

The Explanation from https://github.com/wp-pay-gateways/sisow/blob/develop/documentation/rest540-en.pdf:

> No PayPal API data found in the Sisow profile

After entering PayPal API data in the Sisow dashboard I was able to initiate a payment.

![www sisow nl_Sisow_portal_Simulator aspx_merchantid=2537541595 txid=TEST90757699172 sha1=4017bff3095cd027ad01abe8d70cdedeaa739030](https://user-images.githubusercontent.com/869674/122770059-5e644b00-d2a5-11eb-80ca-caa61d72d447.png)

**Comment by remcotolsma** [comment]
I just checked https://github.com/wp-pay-gateways/digiwallet, there was no PayPal support implemented, just added this in https://github.com/wp-pay-gateways/digiwallet/commit/fca8fb9941a9c2e1b59e3aad0de5b8c34545348f. When starting a PayPal payment via DigiWallet I currently get the following error:

```
DW_IE_0001 Unknown internal error
```

Probably caused by the PayPal payment method not being active within our DigiWallet test account:

![www digiwallet nl_nl_organization_141722_payment-methods](https://user-images.githubusercontent.com/869674/122772498-bd2ac400-d2a7-11eb-9150-7159ab723885.png)

I was also unable to activate the PayPal payment method, but I am confident that it will work.

**Comment by remcotolsma** [comment]
I just checked https://github.com/wp-pay-gateways/payvision, currently the PayPal payment method is not supported:
https://github.com/wp-pay-gateways/payvision/blob/b61967ac363ee8eff9f57922cfde62787944801f/src/Gateway.php#L80-L90

We do convert the core payment method to a Payvision brand ID:
https://github.com/wp-pay-gateways/payvision/blob/b61967ac363ee8eff9f57922cfde62787944801f/src/BrandId.php#L90-L91

If i enable the PayPal method and start a payment i see the following error on https://test.ppipe.net/connectors/simulator;jsessionid=D0973CD43E4348DD52A038671AE3DA1A.uat01-vm-con02.

```
Parameter with name <b>cmd</b> is missing in redirection.<br>Parameter with name <b>connector</b> is missing in redirection.<br>Parameter with name <b>ndcid</b> is missing in redirection.<br>Parameter with name <b>token</b> is missing in redirection.<br>Parameter with name <b>useraction</b> is missing in redirection.<br>
```

This looks like an error with Payvision, but maybe we don't have the minimum required parameters:
https://developers.acehubpaymentservices.com/docs/paypal

**Comment by remcotolsma** [comment]
I just tested https://github.com/wp-pay-gateways/pay-nl, this is working.

![Schermafbeelding 2021-06-21 om 21 59 28](https://user-images.githubusercontent.com/869674/122820606-157bb900-d2dc-11eb-8980-08e0667f5f30.png)

**Comment by rvdsteege** [comment]
Just tested this with https://github.com/wp-pay-gateways/mollie, working as expected in test mode.

<img width="459" alt="Schermafbeelding 2021-06-30 om 11 36 33" src="https://user-images.githubusercontent.com/10371164/123938590-8899c500-d997-11eb-8feb-45e86b013309.png">
<img width="952" alt="Schermafbeelding 2021-06-30 om 11 35 52" src="https://user-images.githubusercontent.com/10371164/123938604-8b94b580-d997-11eb-9087-671555cd4a09.png">

**Comment by remcotolsma** [comment]
I just tested EMS e-Commerce, unfortunately, it is not possible to successfully start a PayPal test payment with our EMS test account.

**Goedkeuringscode** N:-5002:brand not supported
**Status** MISLUKT
**Mislukt reden** Kaartype, merk of dienst wordt niet ondersteund door onderneming. Probeer het met een andere kaart.

![pay local_wp-admin_post php_post=480 action=edit](https://user-images.githubusercontent.com/869674/123971870-b04e5480-d9ba-11eb-83f5-21b5a04302bd.png)

Created a new issue for this: https://github.com/pronamic/wp-pronamic-pay/issues/172.

**Comment by remcotolsma** [comment]
Also checked ICEPAY, currently no support for PayPal:
https://github.com/wp-pay-gateways/icepay/blob/9ce8fbe5daae6ed0183f28ef6f733011e95f2832/src/Gateway.php#L154-L167

However, they do offer the PayPal payment method: https://icepay.nl/betaalmethoden/paypal/.

Created a new issue for this: https://github.com/pronamic/wp-pronamic-pay/issues/173.

**Comment by rvdsteege** [comment]
ING Kassa Compleet supports PayPal:

- https://github.com/wp-pay-gateways/ing-kassa-compleet/blob/2.1.1/src/Gateway.php#L92

However, I've just deprecated this gateway in https://github.com/wp-pay-gateways/ing-kassa-compleet/commit/852ced54aa2917a4ad2811821db6e33e4be94d96 (in favour of the Payvision gateway), as the API at api.kassacompleet.nl is not available anymore.

**Comment by rvdsteege** [comment]
MultiSafepay integration seems to supports PayPal:
- https://github.com/wp-pay-gateways/multisafepay/blob/2.1.3/src/Gateway.php#L165

However, I was unable to test this as the PayPal method is not enabled for our testing account. I've requested activation of this method via integration@multisafepay.com — awaiting reply.

**Comment by rvdsteege** [comment]
> MultiSafepay integration seems to supports PayPal. However, I was unable to test this as the PayPal method is not enabled for our testing account. I've requested activation of this method via [integration@multisafepay.com](mailto:integration@multisafepay.com) — awaiting reply.

Tested successfully in #179.

**Comment by jelkeboonstra** [comment]
A WooCommerce PayPal payment in combination with Adyen isn't working. The user gets redirected to the 'Order received' page without getting redirected to the PayPal environment. Tested it with the overall and general 'Pronamic' payment method.

**Comment by remcotolsma** [comment]
> A WooCommerce PayPal payment in combination with Adyen isn't working. The user gets redirected to the 'Order received' page without getting redirected to the PayPal environment. Tested it with the overall and general 'Pronamic' payment method.

New issue for Adyen: https://github.com/pronamic/wp-pronamic-pay/issues/180.

The original question of this issue is answered:

> Is the PayPal payment method supported in all the gateways?
