### ISSUE TITLE
Extend PayPal support in extensions

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#146]
Is the PayPal payment method supported in all the extensions? 

- [x] https://github.com/wp-pay-extensions/charitable
- [x] https://github.com/wp-pay-extensions/contact-form-7
- [x] https://github.com/wp-pay-extensions/easy-digital-downloads
- [x] https://github.com/wp-pay-extensions/event-espresso
- [x] https://github.com/wp-pay-extensions/event-espresso-legacy
- [x] https://github.com/wp-pay-extensions/formidable-forms
- [x] https://github.com/wp-pay-extensions/give
- [x] https://github.com/wp-pay-extensions/gravityforms
- [x] https://github.com/wp-pay-extensions/memberpress
- [x] https://github.com/wp-pay-extensions/ninjaforms
- [x] https://github.com/wp-pay-extensions/restrict-content-pro
- [x] https://github.com/wp-pay-extensions/s2member
- [x] https://github.com/wp-pay-extensions/woocommerce
- [x] https://github.com/wp-pay-extensions/wp-e-commerce

_Internal Basecamp to-do:_ https://basecamp.com/1810084/projects/10966871/todos/335230956

**Comment by rvdsteege** [comment]
I've checked all extensions and added support for PayPal payment method in:

- Charitable » https://github.com/wp-pay-extensions/charitable/compare/017389f...895de9c
- Give » https://github.com/wp-pay-extensions/give/commit/097d86caf3f19c1416291779a2d26a51cef6f5e0

Do we want to add support in the **legacy** Event Espresso integration? I'd leave it out.

**Comment by remcotolsma** [comment]
As far as I'm concerned, it's fine to leave https://github.com/wp-pay-extensions/event-espresso-legacy out for now.
