### ISSUE TITLE
Few suggestions for refund functionality

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay#152]
It was a great initiative to add a refund option in the wp-pay core library. I have few suggestions for the same.

1. I can see that currently error/exception is not handled in case any issue occurs while creating a refund (in `$gateway->create_refund`). are you planning to handle errors after this function?
https://github.com/wp-pay/core/blob/c69d05c3507d5ca15f7a85d380f721e9a7ff460e/src/Plugin.php#L1093

2. In Mollie gateway, I can see that the payment object is fetched from the transaction id. If we will see other functions like `start` and `update_status`, $payment is passed as a parameter and is getting used directly. I think in almost all the payment gateways, a payment object will be needed for initiating the refund. Wouldn't it be great if we will fetch the payment object in the Plugin class and pass it as a parameter, instead of transaction id. It will reduce rework in all the other gateways. What do you think about it?
https://github.com/wp-pay-gateways/mollie/blob/d58e58f1d0d748f33baa5486f9741f47a2a64c77/src/Gateway.php#L851

3. Refunded amount is getting update in `update_status` function. Shouldn't we update it while creating refund in `create_refund` function?
https://github.com/wp-pay-gateways/mollie/blob/d58e58f1d0d748f33baa5486f9741f47a2a64c77/src/Gateway.php#L770

4. Should the status of payment be marked as "REFUNDED" in `create_refund` function.

5. Are you planning to handle both Partial and Full refunds?

**Comment by remcotolsma** [comment]
We are improving the refunds API in https://github.com/pronamic/wp-pay-core/pull/111, we think we have addressed the questions/comments within this issue there. If you see any points for improvement, please let us know, pull requests for improvements are always welcome.
