### ISSUE TITLE
Introduce `pronamic/wp-pay-coding-standards` library?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#163]
I noted that some WordPress development agencies have their own coding standards repository:

- https://github.com/10up/phpcs-composer
- https://github.com/humanmade/coding-standards
- https://github.com/WebDevStudios/php-coding-standards
- https://github.com/Yoast/yoastcs
- https://github.com/inpsyde/php-coding-standards
- https://github.com/Automattic/VIP-Coding-Standards
- https://github.com/Automattic/phpcs-neutron-ruleset
- https://github.com/Automattic/phpcs-cobalt-standard
- https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset
- https://github.com/slevomat/coding-standard
- https://github.com/wearerequired/coding-standards
- https://github.com/WordPress/WordPress-Coding-Standards

For a more DRY approach it might be a good idea to introduce a `pronamic/wp-pay-coding-standards` or `pronamic/wp-coding-standards` library.

That could reduce some of the Composer requirements?

- `automattic/vipwpcs`
- `dealerdirect/phpcodesniffer-composer-installer`
- `phpcompatibility/php-compatibility`
- `phpcompatibility/phpcompatibility-wp`
- `squizlabs/php_codesniffer`
- `wp-coding-standards/wpcs`

Just require `pronamic/wp-coding-standards` and all the rules we use are available?

@rvdsteege what are your thoughts on this?

**Comment by rvdsteege** [comment]
👍 A `pronamic/wp-coding-standards` (our coding standards are company wide) sounds good:

1. keeps the Composer configuration clean;
2. only need to edit one file to update these dependencies for all projects.

**Comment by remcotolsma** [comment]
🎉 https://github.com/pronamic/wp-coding-standards
