### ISSUE TITLE
Send Level 2/3 data for Adyen card payments

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#167]
From customer:

> Wij lopen tegen hoge fees aan voor transacties in USA. Nu adviseert Adyen ons om level 2/3 data mee te sturen als additional field.

It is suggested to reduce payment fees with Adyen by sending additional purchase data for commercial card payments:

> Level 2 or Level 3 (L2/L3) data provides commercial shoppers with additional information about purchases on their card statements. It allows companies to track how much is spent on their corporate cards where a single card may have multiple users.
Companies can also track the amount of sales tax to pay or reconcile transactions using a unique customer code. Transactions submitted with L2/L3 data that meet requirements have lower interchange rates.

- https://docs.adyen.com/payment-methods/cards/send-additional-data-for-cards/send-level-2-3-data-for-commercial-cards

Sample additional data from the mentioned documentation:

```
  "additionalData": {
    "enhancedSchemeData.totalTaxAmount": "24000",
    "enhancedSchemeData.customerReference": "101",
    "enhancedSchemeData.freightAmount": "300",
    "enhancedSchemeData.destinationStateProvinceCode": "NYC",
    "enhancedSchemeData.shipFromPostalCode": "1082GM",
    "enhancedSchemeData.orderDate": "101216",
    "enhancedSchemeData.destinationPostalCode": "1082GM",
    "enhancedSchemeData.destinationCountryCode": "NLD",
    "enhancedSchemeData.dutyAmount": "500",
    "enhancedSchemeData.itemDetailLine1.description": "T15 Test products 1",
    "enhancedSchemeData.itemDetailLine1.productCode": "TEST120",
    "enhancedSchemeData.itemDetailLine1.commodityCode": "COMMCODE1",
    "enhancedSchemeData.itemDetailLine1.quantity": "5",
    "enhancedSchemeData.itemDetailLine1.unitOfMeasure": "m",
    "enhancedSchemeData.itemDetailLine1.unitPrice": "1000",
    "enhancedSchemeData.itemDetailLine1.discount": "60",
    "enhancedSchemeData.itemDetailLine1.totalAmount": "4940",
    "enhancedSchemeData.itemDetailLine2.description": "T15 Test products 2",
    "enhancedSchemeData.itemDetailLine2.productCode": "TEST120",
    "enhancedSchemeData.itemDetailLine2.commodityCode": "COMMCODE2",
    "enhancedSchemeData.itemDetailLine2.quantity": "5",
    "enhancedSchemeData.itemDetailLine2.unitOfMeasure": "m",
    "enhancedSchemeData.itemDetailLine2.unitPrice": "1000",
    "enhancedSchemeData.itemDetailLine2.discount": "60",
    "enhancedSchemeData.itemDetailLine2.totalAmount": "4940",
    "enhancedSchemeData.itemDetailLine3.description": "T15 Test products 3",
    "enhancedSchemeData.itemDetailLine3.quantity": "5",
    "enhancedSchemeData.itemDetailLine3.productCode": "TEST120",
    "enhancedSchemeData.itemDetailLine3.commodityCode": "COMMCODE3",
    "enhancedSchemeData.itemDetailLine3.unitOfMeasure": "m",
    "enhancedSchemeData.itemDetailLine3.unitPrice": "1000",
    "enhancedSchemeData.itemDetailLine3.discount": "60",
    "enhancedSchemeData.itemDetailLine3.totalAmount": "4940"
  }
```

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/1553720692/22265_

**Comment by rvdsteege** [comment]
I have just sent a request to Adyen support (ticket #2210366) to enable the `cardSchemeEnhancedDataLevel` parameter in the additional data response, so we can verify if Level 2/3 data is included correctly when starting a payment.

From [the documentation](https://docs.adyen.com/payment-methods/cards/send-additional-data-for-cards/send-level-2-3-data-for-commercial-cards#sending-level-23-data):
> To enable the `cardSchemeEnhancedDataLevel` parameter for your account, contact the Support Team. You can submit L2 and L3 data without enabling this parameter. If it is enabled, and the card supports L2/L3 data, the response contains a `cardSchemeEnhancedDataLevel` parameter set to either `L2` or `L3`.

**Comment by rvdsteege** [comment]
For Level 2/3 data, only the following parameters are required:

1. `enhancedSchemeData.customerReference`
2. `enhancedSchemeData.totalTaxAmount`
3. `enhancedSchemeData.destinationPostalCode` (only required for Amex)

Since https://github.com/wp-pay-gateways/adyen/compare/070b204...b475c8d, the following data is included (if available) when creating a payment:

- `enhancedSchemeData.customerReference` (empty string)
- `enhancedSchemeData.destinationPostalCode`
- `enhancedSchemeData.destinationCountryCode`
- `enhancedSchemeData.freightAmount`
- `enhancedSchemeData.orderDate`
- `enhancedSchemeData.totalTaxAmount`
- `enhancedSchemeData.itemDetailLineX.description`
- `enhancedSchemeData.itemDetailLineX.productCode`
- `enhancedSchemeData.itemDetailLineX.quantity`
- `enhancedSchemeData.itemDetailLineX.totalAmount`

**Comment by rvdsteege** [comment]
Reply from Adyen with clarification regarding the customer reference:

> As for the `customerReference` - you can add your own (internal) reference/ customer code. Please note the max length is 25 characters.

Based on the description in the docs for the customer reference _("Customer code, if supplied by a customer.")_, I assumed customer reference was meant to be something like a purchase order ID. As we don't get something like that from for example WooCommerce, I'm setting an empty string instead.

Maybe we should use the WordPress user ID as customer reference? If the user is not logged in, we can use the empty string instead.

@remcotolsma thoughts?

**Comment by remcotolsma** [comment]
As far as I'm concerned, let's leave this for what it is, this has not come up in recent months. Adyen has also confirmed that they are no longer focusing on WordPress and/or WooCommerce.

> Het is op dit moment niet meer iets waar ik me op focus, **daarnaast is Wordpress / woo commerce ook geen platform meer waar we ons actief op richten**.

☹️

- https://github.com/pronamic/pronamic-pay/issues/35
