### ISSUE TITLE
Investigate chargeback support at payment providers

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#170]
We are investigating how we can add support for chargebacks. With a short summary per gateway we can hopefully come to a nice solution.

- [x] https://github.com/wp-pay-gateways/adyen
- [x] https://github.com/wp-pay-gateways/buckaroo
- [x] https://github.com/wp-pay-gateways/digiwallet
- [x] https://github.com/wp-pay-gateways/ems-e-commerce
- [x] https://github.com/wp-pay-gateways/icepay
- [x] https://github.com/wp-pay-gateways/ideal
- [x] https://github.com/wp-pay-gateways/ideal-advanced-v3
- [x] https://github.com/wp-pay-gateways/ideal-basic
- [x] https://github.com/wp-pay-gateways/mollie
- [x] https://github.com/wp-pay-gateways/multisafepay
- [x] https://github.com/wp-pay-gateways/ogone
- [x] https://github.com/wp-pay-gateways/omnikassa-2
- [x] https://github.com/wp-pay-gateways/pay-nl
- [x] https://github.com/wp-pay-gateways/payvision
- [x] https://github.com/wp-pay-gateways/sisow
- [x] https://github.com/wp-pay-gateways/targetpay

**Comment by remcotolsma** [comment]
We already know from Mollie that they have support for chargebacks:
https://docs.mollie.com/reference/v2/chargebacks-api/get-chargeback#

Mollie keeps track of the `amountChargedBack` value per payment.
https://docs.mollie.com/reference/v2/payments-api/get-payment

> The total amount that was charged back for this payment. Only available when the total charged back amount is not zero.

In https://github.com/wp-pay-gateways/mollie/blob/09c60fdfbab9eee85d58909da24c5b82d9ff51fe/src/Gateway.php#L734-L767 we already request the payment chargebacks.

**Comment by remcotolsma** [comment]
The iDEAL only gateways don't have support for chargebacks:

> iDEAL is an Online Banking Payment method based on a four-corner model which generates a SEPA Credit Transfer from within the consumers trusted online banking portal. By using iDEAL consumers are able to pay for their online purchases in a user-friendly, cost-efficient and secure fashion. Merchants receive real-time confirmations of the **iDEAL payments** which are **guaranteed** and **irrevocable**.

_Source:_ https://www.ideal.nl/en/ideal-information/

**Comment by remcotolsma** [comment]
At DigiWallet I only see a mention of a payment status `Chargeback` on https://www.digiwallet.nl/en/documentation/:

![www digiwallet nl_en_documentation_paymethods_directdebit](https://user-images.githubusercontent.com/869674/123640583-9b8a8900-d821-11eb-8394-78096b582b3b.png)

- `Chargeback`  the payment has been reversed by the customer.

I assume they only support full chargebacks, we could double check with the DigiWallet support department.

**Comment by rvdsteege** [comment]
Adyen sends notifications for disputes which include the charged back amount. Each status of the dispute process has a unique `eventCode` in the notification:
- https://docs.adyen.com/risk-management/disputes-api/dispute-notifications

A dispute starts with a:
> - **(optional) Notification of Fraud (NOF)** - To notify you of fraud activity, Adyen sends equivalent of a Visa TC40 and Mastercard SAFE (System to Avoid Fraud Effectively) report. This is not a dispute, and no money is withdrawn from your account.
> - **(optional) Request for Information (RFI)** -  Issuer requests more information about a transaction, no money is withdrawn from merchant account.
> - **Notification of Chargeback (NoC)** - A chargeback has been initiated by the issuer, and can be defended. The NoC may follow a RFI, or occur immediately after the payment status is set to Settled or Refunded, skipping the RFI step.

From there, the dispute continues through the following statuses:

> 1. **1st Chargeback** - The disputed amount is withdrawn from your account. If you accept the dispute, or fail to upload your defense documents, this is the final status.
> 2. **InformationSupplied** - Adyen receives the supporting documents and forwards them to the scheme. It is no longer possible to change these documents.
> 3. **ChargebackReversed** - The disputed amount is transferred back to your account. In this stage, the issuer reviews the defense. If they accept the defense, this is the final status.
> 4. **Pre-arbitration (Only Visa, MC,Diners, and Discover)** - If the issuer declines your defense, they open pre-arbitration, which Adyen will review. 
> 5. **2nd Chargeback** - If the issuer declines your defense, or Adyen accepts their pre-arbitration case, a second chargeback occurs. You can not upload defense documents. This is the final status.

[Sample notification](https://docs.adyen.com/risk-management/disputes-api/dispute-notifications#chargeback) for `CHARGEBACK` event:

```json
{
   "live":"true",
   "notificationItems":[
      {
         "NotificationRequestItem":{
            "additionalData":{
               "chargebackReasonCode":"10.4",
               "modificationMerchantReferences":"",
               "chargebackSchemeCode":"visa"
            },
            "amount":{
               "currency":"EUR",
               "value":1000
            },
            "eventCode":"CHARGEBACK",
            "eventDate":"2020-03-23T13:55:31+01:00",
            "merchantAccountCode":"YOUR_MERCHANT_ACCOUNT",
            "merchantReference":"XXXXXXXXXX",
            "originalReference":"9913333333333333",
            "paymentMethod":"visa",
            "pspReference":"9915555555555555",
            "reason":"Other Fraud-Card Absent Environment",
            "success":"true"
         }
      }
   ]
} 
```

Including `originalReference` in the `SECOND_CHARGEBACK` and `CHARGEBACK_REVERSED` event notifications can be enabled in the **Account » Webhooks** settings in the customer area.

**Comment by rvdsteege** [comment]
At Buckaroo, I've found the following references for chargebacks:

1. transaction type `N505` "Creditcard Chargeback" for creditcard payment method, I assume this is `TransactionType` in a request to [json/Transaction/Status/{transactionKey}](https://testcheckout.buckaroo.nl/json/Docs/Api/GET-json-Transaction-Status-transactionKey), I expect the amount of a transaction with this type is the charged back amount;
2. the [`InvoiceStatusCode`](https://dev.buckaroo.nl/AdditionalServices/Description/creditmanagement#invoicestatuscode) of an invoice (which we don't use currently):
> `InvoiceStatusCode`: The current status of the invoice.
> - Possible Status codes are:
>   - [...]
>   - 21: PausedByDispute. Like Paused, but specifically caused by a manually registered dispute.

**Comment by rvdsteege** [comment]
I was unable to find any API related information regarding chargebacks at EMS.

However, one sentence of note found in a [Card Acceptance Operating Guide](https://emspay.nl/sites/emspay.nl/files/support-topics/ems_handleiding_kaartacceptatie_cnp_nl-en_2019-1_0.pdf) regarding chargebacks and recurring payments (emphasis mine):
> If a request for Authorisation has been denied or if transactions previously resulted in a Chargeback to you, **you should terminate the recurring transaction arrangement**.

With Mollie, we are 'terminating' (_On Hold_ status) subscriptions if a chargeback occurs.

**Comment by rvdsteege** [comment]
ICEPAY updates the status of a payment to `CBACK` if a payment was charged back by the end user.

- https://icepay.com/downloads/tech-docs/ICEPAY_API_Guide.pdf

**Comment by rvdsteege** [comment]
In https://github.com/pronamic/wp-pronamic-pay-ems-e-commerce/issues/1 we noticed that the EMS integration seems to be outdated. In the documentation of our current integration, there is no mention of chargebacks.

In the documentation of the new integration, it seems that multiple chargebacks can be linked to a payment (`chargeback_orders`), which would mean it supports partial chargebacks.
- https://emspay.stoplight.io/docs/online/51ecb90a34498-get-a-single-order

> `chargeback_of_order_id` _string_
> Order identifier of the original order, if this is a chargeback
>
> `chargeback_orders` _array[string]_
> Order identifiers of the related chargeback orders

**Comment by rvdsteege** [comment]
With MultiSafepay, [documentation of the deprecated XML API](https://www.pronamic.nl/wp-content/uploads/2014/01/Handleiding_connectENG.pdf) does not mention chargebacks.

With the [current JSON API](https://docs-api.multisafepay.com/), there are separate order and transaction statuses. According to the [payment statuses documentation](https://docs.multisafepay.com/payments/payment-statuses/), both statuses will be set to `Void` if the customer has requested a chargeback. Once the chargebacks has been 'completed', the statuses of both the order and transaction will be updated to `Completed`.

It seems there is no specific order property for the chargeback amount. However, it could be that a chargeback results in a new order (with its own order ID) which contains a partial amount. This is how refunds are handled:
- https://docs-api.multisafepay.com/reference/refundorder

**Comment by rvdsteege** [comment]
Ingenico includes chargebacks in _the daily reporting files_:

> A chargeback is processed by us and will be reported as a chargeback (CB record) in the daily reporting files (WX.file and in the Appendix of the Collection Reports). These reporting files should be well integrated with your own Internal Order System in order to quickly identify the chargeback and take the appropriate action.
>
> […]
>
> Another method to retrieve chargebacks is by downloading a report in the WebCollect Payment Console. Under Reports/Transaction Reports you will find ‘Chargeback/Reversal’ and from there you can download all the reported chargebacks for a specific time frame.

_Source: https://epayments.developer-ingenico.com/services/chargebacks_

According to https://epayments-support.ingenico.com/en/integration-solutions/integrations/directlink#directlink_integration_guides_order_response there is no chargeback amount in the order, but I'm not sure if a chargeback could be derived from the order response (e.g. through `NCERROR` or `NCSTATUS`).

**Comment by rvdsteege** [comment]
For OmniKassa 2.0, I couldn't find any documentation regarding chargebacks.

Order results received through notifications contain a `paidAmount` and `totalAmount`. However, I'm not sure if chargebacks (1) trigger a webhook notification and (2) these amounts in the order result differ if a chargeback occurred.

**Comment by rvdsteege** [comment]
At Pay.nl, there's only mention of `storno` at https://admin.pay.nl/docpanel/api/Transaction/info/4 but this looks like a refund and not a chargeback.

> `paymentDetails.storno` integer
> Indicator whether or not the transaction is refunded
> - `0`: Non refunded
> - `1`: Refundend
>
> `stornoDetails` array
> > `stornoAmount`: Refund amount
> > […]

**Comment by rvdsteege** [comment]
At Sisow, a transaction can have the status `Reversed`. However, it is unclear when this status is actually used. We have it mapped to our payment refunded status.

**Comment by rvdsteege** [comment]
Targetpay mentions a transaction status `000003 Chargeback - The money has been chargebacked by the customer` in the direct debit documentation. No mention of a separate chargeback amount.

- https://www.targetpay.com/info/directdebit-docu
