### ISSUE TITLE
Add support for PayPal in Adyen gateway

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#180]
_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1590353532/22475/

Test payment: https://woocommerce-adyen.wp-pay.org/wp-admin/post.php?post=3235&action=edit

https://docs.adyen.com/payment-methods/paypal/web-drop-in

**Comment by remcotolsma** [comment]
Re-informed in internal support ticket https://secure.helpscout.net/conversation/1624958858/22690?folderId=1425710.

**Comment by remcotolsma** [comment]
Some work-in-progress in https://github.com/wp-pay-gateways/adyen/commit/97d892980fda63bc74bd97a4d790af1551c576e6 by @rvdsteege, but it's not working, i will have a look at this.

**Comment by rvdsteege** [comment]
Improvements by @remcotolsma in https://github.com/wp-pay-gateways/adyen/compare/97d8929...d6b1098

I just fixed redirecting to payment status page after PayPal payment has been completed:
- https://github.com/wp-pay-gateways/adyen/commit/c21fffc1849c8c65f8a007c4c0c9336a6cdcb056
