### ISSUE TITLE
Support Mollie Orders API for Klarna Pay Later and Klarna Slice It methods

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#190]
Klarna Pay Later and Klarna Slice It (and vouchers) are currently not supported for Mollie, as these require using the Orders API.

- https://docs.mollie.com/orders/overview

**Comment by rvdsteege** [comment]
Also required for **Klarna Pay now**.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/1773692826/23434_

**Comment by remcotolsma** [comment]
Some more details in internal / private Basecamp to-do:
https://basecamp.com/1810084/projects/10966871/todos/384902142

**Comment by remcotolsma** [comment]
A customer inquired about this again:

> Hope you are doing well.
> I came back again for 2nd time on the topic that we discussed a few months back.
> 
> The two payment Klarna payment methods "Klarna Pay Later" (in German "Klarna Rechnungskauf"?) and "Klarna Slice It" (in German "Klarna Ratenkauf"?) are currently not supported in the Pronamic Pay plugin.
> 
> We already went into production last October 2021 without them.

https://secure.helpscout.net/conversation/1915990137/24057/

**Comment by remcotolsma** [comment]
I created https://github.com/pronamic/wp-pronamic-pay-mollie/tree/orders-api-for-klarna branch for developing this feature.

**Comment by remcotolsma** [comment]
This is merged in: https://github.com/pronamic/wp-pronamic-pay-mollie/pull/4.
