### ISSUE TITLE
Fundraising blocks broken

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#204]
Currently, (some of?) the fundraising blocks are broken. Probably since WordPress `5.8`.

<img width="637" alt="Schermafbeelding 2021-09-06 om 09 12 09" src="https://user-images.githubusercontent.com/10371164/132175558-9966ba51-bc31-4ed4-ba73-236a6509aee1.png">

<img width="1962" alt="Schermafbeelding 2021-09-06 om 09 11 50" src="https://user-images.githubusercontent.com/10371164/132175569-fbd92aa3-5d11-4839-8982-4f7d9ece114b.png">

**Comment by remcotolsma** [comment]
Discussed we're going to fix this, initially max ~ 2 hours of work.
