### ISSUE TITLE
Subscriptions follow-up payments problem due to slow database / lots of metadata

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#212]
We have a customer with many payments and subscriptions where the start-up of the follow-up payments is not going well. At first, the slow server/database seemed to be causing problems, but adding a temporary index on the `wp_postmeta.meta_value` may have played a role as well. However, this issue may be a signal that not all WordPress installations are stable enough to initiate subscription follow-up payments. I don't think it's the first time that this doesn't run as smoothly as we'd like. The [WordPress cron](https://developer.wordpress.org/plugins/cron/) doesn't always seem to work well for this. The big question is how are we going to fix/improve this? Is it better to use the [Mollie Subscriptions API](https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription)?

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/1637278281/22756?folderId=1425710

**Comment by remcotolsma** [comment]
This issue is not completely new, we have the following internal Basecamp to-do open for this: [Abonnementen » Dubbele betalingen mogelijk bij dubbele cron](https://basecamp.com/1810084/projects/10966871/todos/424598545#comment_778334652). A possible solution is also to make more use of custom tables and to [lock](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html) rows while starting up a follow-up payment.

**Comment by remcotolsma** [comment]
We wrote 2 Mollie CLI commands to help cancel payments.

```
wp pronamic-pay mollie payments list --api_key=live_●●●●●●●●●●●●●●●●●●●●●●●●●●●●●● --is_cancelable --format=ids`
```

```
wp pronamic-pay mollie payments cancel $( wp pronamic-pay mollie payments list --api_key=live_●●●●●●●●●●●●●●●●●●●●●●●●●●●●●● --is_cancelable --format=ids ) --api_key=live_●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
```

**Comment by remcotolsma** [comment]
**Advantages Mollie Subscriptions API**

- Follow-up payments no longer depend on WordPress (cron).
- Test / staging environments will no longer initiate follow-up payments.
- Subscriptions could be displayed in the Mollie dashboard or other tools.
- Other payment gateways like PayPal and Stripe work in a similar way.

**Disadvantages Mollie Subscriptions API**

- ?

Are there any real drawbacks?

**Comment by rvdsteege** [comment]
**Disadvantages Mollie Subscriptions API**

- Payment method changes not possible?
  1. allow _any_ mandate to be used instead or
  2. cancel and create new subscription.
- Pause/resume subscriptions not possible?
  1. cancel and create new subscription instead.
- Intervals can only be specified in days/weeks/months, not as advanced PHP date interval.

**Comment by remcotolsma** [comment]
### Option 2 - One global daily schedule event that schedules single events for each follow-up payment

> **Note that scheduling an event to occur within 10 minutes of an existing event with the same action hook will be ignored** unless you pass unique `$args` values for each scheduled event.

https://developer.wordpress.org/reference/functions/wp_schedule_single_event/

The advantage of this may also be that if a follow-up payment cannot be started at the gateway, we can reschedule the single event. I'm not exactly sure what WordPress does with events that throw an exception. It might not be watertight yet, but this option might solve some issues.

@rvdsteege You mentioned that WooCommerce also schedules events for orders, i couldn't find this: https://github.com/woocommerce/woocommerce/search?q=wp_schedule_single_event.

**Comment by rvdsteege** [comment]
> You mentioned that WooCommerce also schedules events for orders, i couldn't find this.

It's here:
- https://github.com/woocommerce/woocommerce-admin/blob/6865aac06f970c5642d03be1476637e5cca26300/src/Schedulers/SchedulerTraits.php#L289-L316

<img width="961" alt="Schermafbeelding 2021-09-29 om 11 18 10" src="https://user-images.githubusercontent.com/10371164/135240569-5c54eacf-f529-40f0-936c-b5a9f02998ed.png">

**Comment by remcotolsma** [comment]
@rvdsteege made a overview of meta usage:

### Pronamic Pay meta

#### Payments

```sql
select p.ID, p.post_title, m.meta_key, m.meta_value from wp_posts as `p` left join wp_postmeta as `m` ON m.post_id = p.ID where p.post_type=‘pronamic_payment’ and m.meta_key LIKE ‘_pronamic%’ group by m.meta_key order by m.meta_key ASC
```

| Key | In JSON | In post meta |
| --- | ------- | ------------ |
| `_pronamic_payment_action_url` | :x: | :white_check_mark: |
| `_pronamic_payment_address` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_adyen_details_result` | :x: | :white_check_mark: |
| `_pronamic_payment_adyen_payment_response` | :x: | :white_check_mark: |
| `_pronamic_payment_adyen_sdk_version` | :x: | :white_check_mark: |
| `_pronamic_payment_amount` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_city` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_config_id` | :x: | :white_check_mark: |
| `_pronamic_payment_consumer_account_number` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_consumer_bic` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_consumer_iban` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_consumer_name` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_country` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_currency` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_customer_name` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_description` | :x: | :white_check_mark: |
| `_pronamic_payment_email` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_end_date` | :white_check_mark: (also through periods) | :white_check_mark: |
| `_pronamic_payment_entrance_code` | :x: | :white_check_mark: |
| `_pronamic_payment_first_name` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_issuer` | :x: | :white_check_mark: |
| `_pronamic_payment_key` | :x: | :white_check_mark: |
| `_pronamic_payment_language` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_last_name` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_locale` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_method` | :x: | :white_check_mark: |
| `_pronamic_payment_mollie_change_payment_state_url` | :x: | :white_check_mark: |
| `_pronamic_payment_mollie_customer_id` | :x: | :white_check_mark: |
| `_pronamic_payment_omnikassa_2_merchant_order_id` | :x: | :white_check_mark: |
| `_pronamic_payment_order_id` | :x: | :white_check_mark: |
| `_pronamic_payment_recurring` | :x: | :white_check_mark: |
| `_pronamic_payment_recurring_type` | :x: | :white_check_mark: |
| `_pronamic_payment_source` | :x: | :white_check_mark: |
| `_pronamic_payment_source_id` | :x: | :white_check_mark: |
| `_pronamic_payment_start_date` | :white_check_mark: (also through periods) | :white_check_mark: |
| `_pronamic_payment_status` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_subscription_id` | :white_check_mark: through periods | :white_check_mark: |
| `_pronamic_payment_telephone_number` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_transaction_id` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_user_agent` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_user_ip` | :white_check_mark: | :white_check_mark: |
| `_pronamic_payment_version` | :x: | :white_check_mark: |
| `_pronamic_payment_woocommerce_payment_method` | :x: | :white_check_mark: |
| `_pronamic_payment_woocommerce_payment_method_title` | :x: | :white_check_mark: |
| `_pronamic_payment_zip` | :white_check_mark: | :white_check_mark: |

#### Subscriptions

```sql
select p.ID, p.post_title, m.meta_key, m.meta_value from wp_posts as `p` left join wp_postmeta as `m` ON m.post_id = p.ID where p.post_type=‘pronamic_pay_subscr’ and m.meta_key LIKE ‘_pronamic%’ group by m.meta_key order by m.meta_key ASC
```

| Key | In JSON | In post meta |
| --- | ------- | ------------ |
| `_pronamic_subscription_amount` | :white_check_mark: through fases | :white_check_mark: |
| `_pronamic_subscription_config_id` | :x: | :white_check_mark: |
| `_pronamic_subscription_currency` | :white_check_mark: through fases | :white_check_mark: |
| `_pronamic_subscription_customer_name` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_description` | :x: | :white_check_mark: |
| `_pronamic_subscription_email` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_end_date` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_expiry_date` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_key` | :x: | :white_check_mark: |
| `_pronamic_subscription_mollie_customer_id` | :x: | :white_check_mark: |
| `_pronamic_subscription_mollie_mandate_id` | :x: | :white_check_mark: |
| `_pronamic_subscription_next_payment` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_next_payment_delivery_date` | :white_check_mark: | :white_check_mark: |
| `_pronamic_subscription_payment_method` | :x: | :white_check_mark: |
| `_pronamic_subscription_source` | :x: | :white_check_mark: |
| `_pronamic_subscription_source_id` | :x: | :white_check_mark: |
| `_pronamic_subscription_start_date` | :white_check_mark: through fases | :white_check_mark: |
| `_pronamic_subscription_status` | :white_check_mark: | :white_check_mark: |

**Comment by remcotolsma** [comment]
I think we can remove the following issues from the [Subscriptions follow-up payments improvement](https://github.com/pronamic/wp-pronamic-pay/projects/8) project:

- https://github.com/pronamic/wp-pronamic-pay/issues/222
- https://github.com/pronamic/wp-pronamic-pay/issues/234
- https://github.com/pronamic/wp-pronamic-pay/issues/243
- https://github.com/pronamic/wp-pronamic-pay/issues/255
- https://github.com/pronamic/wp-pronamic-pay/issues/265
- https://github.com/pronamic/wp-pronamic-pay/issues/266

**Comment by remcotolsma** [comment]
We still have a few open issues in the [Subscriptions follow-up payments improvement](https://github.com/pronamic/wp-pronamic-pay/projects/8) project, but we have already implemented the solution for this issue, so I'm closing this ticket.
