### ISSUE TITLE
Update Bancontact logo

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#216]
Bancontact has an updated logo.

- https://www.bancontact.com/nl/nieuws/het-nieuwe-bancontact-logo-zelfde-kleuren-strakkere-look
- https://github.com/pronamic/wp-pay-logos/tree/1.6.6/src/methods/bancontact

<img width="425" alt="Schermafbeelding 2021-09-28 om 16 47 04" src="https://user-images.githubusercontent.com/10371164/135110726-4bee0a7e-4bb1-4df1-b4cb-3eca07e8fca1.png">

**Comment by remcotolsma** [comment]
Updated in https://github.com/pronamic/wp-pay-core/commit/34a1c187de7c3527e413c99cbf3949065a4777fe.
