### ISSUE TITLE
Optimize `pronamic_pay_update_subscription_payments` to process `10` or `20` subscriptions at a time?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#219]
https://github.com/pronamic/wp-pay-core/blob/develop/src/Subscriptions/SubscriptionsModule.php#L1234

👆 Set `-1` to `10` or `20`?

**Comment by rvdsteege** [comment]
Maybe `10` and then put it in a little loop, to execute the call to `$this->process_subscriptions_follow_up_payment()` multiple times — until script execution times out?
