### ISSUE TITLE
Schedule single event for each follow-up payment?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#220]
### Option 2 - One global daily schedule event that schedules single events for each follow-up payment

> **Note that scheduling an event to occur within 10 minutes of an existing event with the same action hook will be ignored** unless you pass unique `$args` values for each scheduled event.

https://developer.wordpress.org/reference/functions/wp_schedule_single_event/

The advantage of this may also be that if a follow-up payment cannot be started at the gateway, we can reschedule the single event. I'm not exactly sure what WordPress does with events that throw an exception. It might not be watertight yet, but this option might solve some issues.

_Originally posted by @remcotolsma in https://github.com/pronamic/wp-pronamic-pay/issues/212#issuecomment-929909849_

**Comment by rvdsteege** [comment]
In the query via `SubscriptionsModule::process_subscriptions_follow_up_payment()` we now also check if there is no event scheduled yet:

- pronamic/wp-pay-core@52f72e6
