### ISSUE TITLE
Add option to disable `pronamic_pay_update_subscription_payments` schedule event?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#221]

**Comment by remcotolsma** [comment]
I think @rvdsteege  is already working on this.

**Comment by rvdsteege** [comment]
Indeed, added a setting in https://github.com/pronamic/wp-pay-core/commit/901ed772c4ce58a584b5a9ee61c4599d425dba90

<img width="544" alt="Schermafbeelding 2021-09-30 om 14 38 38" src="https://user-images.githubusercontent.com/10371164/135456394-e6c3424b-7260-4042-bcb2-4a231bec3ea3.png">

Notes:
- processing of subscriptions is enabled by default;
- setting is only displayed if either:
  - debug mode is enabled or;
  - processing is still turned off, while not in debugging mode (for increased visibility of the setting when processing is disabled, but this also allows us to disable processing of subscriptions in the future on site url changes and simply add an admin notice with link to settings page to re-enable processing if desired — without first needing to enable debug mode).

Questions:
1. Do we want to completely remove/reschedule the event(s) if the setting gets updated? Or leave the scheduled event and only check the current setting status when the action is being called?
2. Completing subscriptions should also be halted if the setting is disabled?

**Comment by remcotolsma** [comment]
> 1. Do we want to completely remove/reschedule the event(s) if the setting gets updated? Or leave the scheduled event and only check the current setting status when the action is being called?

I think an early return is the easiest in terms of code?

> 2. Completing subscriptions should also be halted if the setting is disabled?

Is that necessary if we want to prevent a test/staging environment from sending emails?

> Enable processing of recurring payments

I'm still wondering if we should change 'Enable processing of recurring payments' to 'Disable processing of recurring payments', that might indicate more that it is enabled by default but that you have the option to disable it.

**Comment by rvdsteege** [comment]
Transformed to 'Disable starting recurring payments at gateway' setting in https://github.com/pronamic/wp-pay-core/commit/e1e0ce63eb3600145e8cab8edc913b800ac564c1

In the `SubscriptionsModule::process_subscriptions_follow_up_payment()` we now also check if there is no event scheduled yet:
- https://github.com/pronamic/wp-pay-core/commit/52f72e61e6a8e554ae91f0bd78b2e320d50a3d59

> Is that necessary if we want to prevent a test/staging environment from sending emails?

It seems not, the `SubscriptionsModule::complete_subscriptions()` also checks if there is no `_pronamic_subscription_next_payment` meta. If processing is disabled, the subscriptions will still have their next payment date meta.
