### ISSUE TITLE
Customer specific: delete subscriptions that are not subscriptions?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#222]

**Comment by rvdsteege** [comment]
Could we use the `_pronamic_subscription_mollie_mandate_id` meta to cleanup? Subscription without mandate are 'incomplete'?

**Comment by remcotolsma** [comment]
No action is required for now, should a customer nevertheless want to remove failed or pending subscriptions, this can be achieved via WP-CLI:

**🚨 Danger Zone 🚨**

```
wp post delete $( wp post list --post_type=pronamic_pay_subscr --post_status=subscr_failed --format=ids )
```
