### ISSUE TITLE
Store `_pronamic_payment_issuer` in JSON

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#229]
Currently the `issuer` property is specific used for iDEAL or creditcard issuers. Therefore it is probably more suitable for payment meta. Should we store this in `payment.meta.ideal_issuer`, `payment.meta.creditcard_issuer` or  `payment.meta.issuer`?

<img width="976" alt="Schermafbeelding 2021-10-04 om 14 15 58" src="https://user-images.githubusercontent.com/869674/135849724-012f951e-3c3e-43e8-a072-239bb964e9d7.png">

https://docs.mollie.com/reference/v2/payments-api/create-payment

@rvdsteege ?

**Comment by rvdsteege** [comment]
`payment.meta.issuer` is fine with me.

I don't think it makes sense to differentiate between `payment.meta.ideal_issuer` and `payment.meta.creditcard_issuer`, as there will usually only be a single issuer in use for a payment.

If there are other parameters (I can't think of any now), we could also consider a `payment.payment_method`:

```
payment {
    "payment_method": {
        "id": "ideal",
        "issuer": "ideal_INGBNL2A"
    }
}
```

But as the issuer value is not a 'registered constant' within the plugin and could be 'any value', I feel it is more appropriate to store it as payment meta.

**Comment by remcotolsma** [comment]
Done:
- https://github.com/pronamic/wp-pay-core/commit/b6cbdd9f1a45244242352d485a1d73d111baf5e0
- https://github.com/pronamic/wp-pay-core/commit/2967af4e28deaa2d5455a290d8110fd67d41da4c
