### ISSUE TITLE
Store `_pronamic_payment_method` in JSON

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#230]
For subscriptions we use `_pronamic_subscription_payment_method` or `subscription.payment_method` should we also use `payment.payment_method` or stick to just simply `payment.method`?

Stripe uses `PaymentIntent.payment_method`:
https://stripe.com/docs/api/payment_intents/object#payment_intent_object-payment_method

Mollie uses `Payment.method`:
https://docs.mollie.com/reference/v2/payments-api/create-payment

@rvdsteege ?

**Comment by rvdsteege** [comment]
@remcotolsma I thought of renaming to `payment.payment_method`.

Just `method` could be _any method_, for example HTTP method `GET`/`POST`. I think `payment_method` is more descriptive.

**Comment by remcotolsma** [comment]
Agree, fixed in https://github.com/pronamic/wp-pay-core/commit/f37160f8c73017e15ad5ba5b799db38009da12fc.
