### ISSUE TITLE
Store `_pronamic_payment_source` in JSON

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#232]
Should we group `_pronamic_payment_source` and `_pronamic_payment_source_id` in a object?

```json
payment {
    "source": {
        "key": "woocommerce",
        "id": "50"
    }
}
```

or keep it more in line what we have now?

```json
payment {
    "source": "woocommerce",
    "source_id": "50"
}
```

@rvdsteege ?

**Comment by rvdsteege** [comment]
I was thinking of grouping it.

**Comment by remcotolsma** [comment]
I think grouping in an object also has advantages, we could also store additional data in addition to a key and id.

```json
payment {
    "source": {
        "key": "woocommerce",
        "id": "50"
    }
}
```

Are `source.key` and `source.id` the most logic names? Or should we go for `source.key` and `source.value` just like meta key and value?

**Comment by rvdsteege** [comment]
`key` and `value` LGTM 👍

**Comment by remcotolsma** [comment]
Done in https://github.com/pronamic/wp-pay-core/commit/e14edf5d0f452e611f08c597f1073de9c9810f25.

**Comment by rvdsteege** [comment]
1. Same for subscriptions?
2. I think post meta can now override the value from the stored JSON, is that desired? Or should we only read from meta as fallback, when the source details are not yet available in the JSON?

**Comment by remcotolsma** [comment]
> 1. Same for subscriptions?

Yes, it's the same for subscriptions, both `Payment` and `Subscription` extend the `PaymentInfo` class.

> 2. I think post meta can now override the value from the stored JSON, is that desired? Or should we only read from meta as fallback, when the source details are not yet available in the JSON?

Good question, it's easier to update post meta than update a JSON property in `post_content`. We will still use `_pronamic_payment_source` and `_pronamic_payment_source_id` for `WP_Query`. And we have some upgrade scripts in place:

- https://github.com/wp-pay-extensions/memberpress/blob/develop/src/Upgrade310.php
- https://github.com/wp-pay-extensions/restrict-content-pro/blob/develop/src/Upgrade216.php

For now i think it's ok that post meta `_pronamic_payment_source` are `_pronamic_payment_source_id` are leading. In the future we can always change this behaviour?
