### ISSUE TITLE
Error on Gateway Configuration Page

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay#268]
Hello Team

Some of my clients are getting errors on the Gateway Configuration page, do you have any idea about the same? Only a few clients getting this error.

[30-Oct-2021 13:39:59 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/g31tiroke5m1/public_html/wp-content/plugins/pronamic-ideal/vendor/pronamic/wp-html/src/Element.php on line 104

**Comment by knit-pay** [comment]
@remcotolsma 

I found the solution. The issue is with the function name `print`. This is a reserved keyword of PHP. That's why it is causing issues in a few PHP versions. Renaming this function to something else will fix the issue

**Comment by rvdsteege** [comment]
Thank you Gautam, I was able to reproduce the issue and have resolved it by renaming the method to `output()` instead.

**Comment by knit-pay** [comment]
Thanks @rvdsteege 
When are you planning to release the next update?

**Comment by rvdsteege** [comment]
We don't know yet. We've made some major performance related optimisations in core for Pronamic Pay 8.0; storing less post meta for example. We're removing/reworking some (legacy/deprecated) `Payment` and `Subscription` properties and need to address some final issues before we can release an update. This will probably take some few weeks.

**Comment by knit-pay** [comment]
Thanks for the information. Waiting to see new version soon :)
