### ISSUE TITLE
Increase minimum WordPress requirement to 5.2?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#271]
Should we increase the minimum WordPress requirement to `5.2`? This is the requirement for https://actionscheduler.org/ which we have now included.

https://github.com/woocommerce/action-scheduler/blob/master/readme.txt#L1-L8

**Comment by rvdsteege** [comment]
WordPress 5.2 was released on May 7, 2019. After 2+ years, at least WordPress 5.2 should be used by now. Increasing the WordPress requirement is fine.

**Comment by rvdsteege** [comment]
Should `Requires PHP` also be updated to `5.6.20`?

**Comment by remcotolsma** [comment]
As far as I'm concerned we require PHP `7.4`, this is already the recommendation from WordPress: https://wordpress.org/about/requirements/. PHP `7.3` only has security support until 6 dec 2021: https://www.php.net/supported-versions.php.

https://github.com/pronamic/wp-pronamic-pay/issues/274
