### ISSUE TITLE
Increase minimum PHP requirement to `7.4`?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#274]
As far as I'm concerned we require PHP `7.4`, this is already the recommendation from WordPress: https://wordpress.org/about/requirements/. PHP `7.3` only has security support until 6 dec 2021: https://www.php.net/supported-versions.php.

_Originally posted by @remcotolsma in https://github.com/pronamic/wp-pronamic-pay/issues/271#issuecomment-961694462_

**Comment by rvdsteege** [comment]
A roughly estimated 70% of Pronamic Pay users seem to use PHP version >= `7.4`, based on support (YTD). The current percentage is probably a little higher.

As active support for PHP 7.4 [ends in 3 weeks](https://www.php.net/supported-versions.php) and WordPress also recommends PHP version `7.4`, I think it's fine to bump the minimum PHP version requirement to `7.4`.

<img width="986" alt="Schermafbeelding 2021-11-05 om 09 37 00" src="https://user-images.githubusercontent.com/10371164/140482040-e5f955ef-98fc-4764-82b6-d0e8c507a799.png">

**Comment by remcotolsma** [comment]
Increased it in https://github.com/pronamic/wp-pronamic-pay/commit/076cdedb2584a07e61a4b3ce95b82cbfab74290e. As soon as we work on extensions and gateways, we can also implement the increase there. No need to apply it everywhere at once.
