### ISSUE TITLE
Completing subscriptions needs update

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#284]
The scheduled action to complete subscriptions uses the `_pronamic_subscription_end_date` post meta to find subscriptions:
- https://github.com/pronamic/wp-pay-core/blob/d8b108bf59b9f9a297a487d30909bb82b8981dc7/src/Subscriptions/SubscriptionsModule.php#L1155-L1165

As we've currently removed this post meta (in development), subscriptions won't be completed anymore.

Possible solutions I can think of:
1. re-add the end date post meta;
2. schedule action to complete a single subscription.

**Comment by remcotolsma** [comment]
I'm leaning towards re-adding the end date in the post meta in `_pronamic_subscription_end_date`. Subscriptions will not always have an end date, so that is probably not too bad in terms of post meta pollution.

@rvdsteege Do you agree or do you have any new insights?

**Comment by rvdsteege** [comment]
Re-adding `_pronamic_subscription_end_date` post meta is fine with me. 

The alternative, scheduling a completion action whenever the end date changes, is also a bit tricky and could result in a lot of scheduled actions for a long time — which is also not really desired.

**Comment by remcotolsma** [comment]
Re-added in https://github.com/pronamic/wp-pay-core/commit/1e19edc75fd5f5d9fa0cfe62b644017307455c13.
