### ISSUE TITLE
Clarify follow-up payments

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#288]
Add tools to make it more clear for users when follow-up payments should be created.

- [x] Next payment date column in subscriptions table
- [ ] Debug page with the next 10 subscriptions that require follow-up payment
- [ ] A calendar overview with all follow-up payments for the upcoming year/month

**Comment by rvdsteege** [comment]
> Next payment date column in subscriptions table

I've added the next payment date column to the subscriptions table.

> Debug page with the next 10 subscriptions that require follow-up payment

Is this the same as the debug page which has been removed recently:
- https://github.com/pronamic/wp-pay-core/commit/1fc2efca7bf58956a2b341c746eca8a0c29cce50?

> A calendar overview with all follow-up payments for the upcoming year/month

I would add something like this to either a Subscriptions or Reporting add-on and leave this out for now.

**Comment by remcotolsma** [comment]
> I've added the next payment date column to the subscriptions table.

🎉

> Is this the same as the debug page which has been removed recently:

Yeah, not relevant anymore.

> I would add something like this to either a Subscriptions or Reporting add-on and leave this out for now.

Allright, will close this issue for now.
