### ISSUE TITLE
Drop support for multiple extensions `event-espresso-legacy`, `s2member`, `wp-e-commerce`

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#293]
In line with #292 we should consider to drop support for:

- https://github.com/wp-pay-extensions/event-espresso-legacy
- https://github.com/wp-pay-extensions/s2member
- https://github.com/wp-pay-extensions/wp-e-commerce

In `8.0` we should add a warning that we drop support, in `8.1` we should remove and also display a dismissable notice.

**Comment by remcotolsma** [comment]
We can also consider removing these extensions in `8.0`, we can display a dismissible admin notice to users who have activated one of these extensions.

```php
if ( \defined( '\WS_PLUGIN__S2MEMBER_VERSION' ) ) {

}
```

```
We notice that you have installed s2Member, support for s2Member has been removed from the Pronamic Pay plugin since version 8.
```

or:

```
We notice that the "s2Member" plugin is active, support for the "s2Member" plugin has been removed from the Pronamic Pay plugin since version 8.
```

We can we track whether the notice has been dismidded via https://developer.wordpress.org/reference/functions/get_user_option/ and https://developer.wordpress.org/reference/functions/update_user_option/.

I think that way we can get rid of this extension the fastest and we can focus more on popular and well-maintained extensions.

What do you think @kjtolsma @LeoOosterloo @rvdsteege?

**Comment by LeoOosterloo** [comment]
I think such a notice (system) is a good idea. We could also use it for notices of improved extensions as add-ons.

```
We notice you use Mollie as payment provider. Install the Pronamic Pay Mollie Add-on to use the latest features like support for WooCommerce Blocks.
```

**Comment by remcotolsma** [comment]
And dropping support for the following extensions in version 8?

- https://github.com/wp-pay-extensions/event-espresso-legacy
- https://github.com/wp-pay-extensions/s2member
- https://github.com/wp-pay-extensions/wp-e-commerce

**Comment by LeoOosterloo** [comment]
If they are not used a lot anymore im fine by dropping support for those.

- https://github.com/wp-pay-extensions/event-espresso-legacy
This version is the 3.x version right? Versuin 4.x is still supported?

**Comment by remcotolsma** [comment]
> This version is the 3.x version right? Version 4.x is still supported?

Correct.

As for WP eCommerce, see https://wpecommerce.org/:

> So long and thanks for all the fish!
> - Douglas Adams
> 
> Seriously though, thanks for all the good times. The WP e-Commerce Plugin was the first WordPress Plugin. It was invented by me Dan Milward, and a bunch of other creatives in Aotearoa, New Zealand. We paved the way for some other Plugins and better solutions like Shopify to serve today's online sellers. Not a bad effort for some kids in Wellington :)
> 
> These days we work almost exclusively on Gamefroot, an online platform that helps young people learn to code, design and develop video games. 
> 
> A big thanks to Jeff Ghazally, Thomas Howard, Alan Han, Ben Huson, Andrew Killen, Edward, Mihai and of course Gary Cao (my main man back in the day) for being the innovators and thought leaders that changed the way things are done! 

Looks like there isn't much life left in WP eCommerce:
https://github.com/wp-e-commerce/WP-e-Commerce

**Comment by rvdsteege** [comment]
Removing in a major update like 8.0 seems reasonable, but suddenly removing support for these extensions without prior notice will probably only result in negative user experiences and additional _emergency support_. We also don't know exactly how many user this will impact.

I'm fine with removing the support now, but think a deprecation announcement would be more user friendly. To prevent this scenario in the future, we might consider including a way to show such announcements in earlier released plugin versions.

**Comment by remcotolsma** [comment]
I suspect that the number of users (for these plugins), who also regularly perform updates, can be counted on a few hands. That is why I am not so afraid of negative user experiences and additional emergency support. If we remove it now, we will benefit immediately. Even though the integrations may still work well, the less code, the less work. 😅 I have announced the removal in the following posts:

- https://www.pronamic.eu/pronamic-pay-support-for-event-espresso-3-removed/
- https://www.pronamic.eu/pronamic-pay-support-for-s2member-removed/
- https://www.pronamic.eu/pronamic-pay-support-for-wp-ecommerce-removed/

It's a start, feel free to improve the posts.
