### ISSUE TITLE
Pronamic Pay 8.0 release blog

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#298]
Similar to https://www.pronamic.nl/?s=Pronamic+Pay, a draft can be found here:
https://docs.google.com/document/d/1E7A8YeU6F8okZ-OICJe2TeAmsVP2-sNxl9qQ819k2a4/edit?usp=sharing

- [ ] Ask Omroep ●●●●● to use them for a use case?
- [ ] Featured image

**Comment by LeoOosterloo** [comment]
I added a concept of the release blog on https://www.pronamic.nl/?p=29142

**Comment by remcotolsma** [comment]
Version `8.0.0` is released → https://github.com/pronamic/wp-pronamic-pay/releases/tag/8.0.0, post is published → https://www.pronamic.nl/2022/01/pronamic-pay-8-0-prestatieverbeteringen-abonnementensysteem/.
