### ISSUE TITLE
Remove methods for error handling with `WP_Error` object

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#303]
In the core gateway, we have methods `get_error()`, `set_error()` and `has_error()` which use a `WP_Error` object for error handling:
- https://github.com/pronamic/wp-pay-core/blob/4.0.1/src/Core/Gateway.php#L141-L167

Most of our error handling has been updated to use exceptions instead. The `set_error()` method is still in use in some gateway `get_issuers()` and `get_available_payment_methods()`, would be nice to use exceptions also for these cases.

**Comment by remcotolsma** [comment]
Removed in https://github.com/pronamic/wp-pay-core/compare/a28fe2a058e447a33939b5333dafe570cb331560...930353dd222b09eda003741f2eeb33006133f699.
