### ISSUE TITLE
Fatal error on unsupported PHP version

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#309]
If the minimum PHP version requirement is not met, a Composer platform check triggers a fatal error:

> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0'. You are running 7.3.33. in /wp-content/plugins/pronamic-ideal/vendor/composer/platform_check.php on line 24

- https://getcomposer.org/doc/07-runtime.md#platform-check

We could improve this, by disabling the Composer platform check and adding our own PHP version check resulting in for example an admin notice.

**Comment by remcotolsma** [comment]
Improved in https://github.com/pronamic/wp-pronamic-pay/commit/d86e46ddeb88e086a6b1ea5359af6ace73585bd7.
