### ISSUE TITLE
Gravity Forms » Alignment payment method icons

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pronamic-pay#312]
The 'Payment methods' fields get a default `gf_list_2col` CSS-class. If i want to change that to `gf_list_3col` or `gf_list_inline` the 2 columns css-class is still added...

<img width="961" alt="Schermafbeelding 2022-02-28 om 16 05 20" src="https://user-images.githubusercontent.com/610613/156006310-af163143-1ce2-4530-8bf7-f81a98eab9d0.png">

The items also get quite some white space in front of them.

Can we change the way we display payment methods when '**list with icons**' '**small icons**' or '**large icons**' is selected?

**Comment by rvdsteege** [comment]
We could maybe change https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/4.0.1/src/PaymentMethodsField.php#L122 to only search for `gf_list_`, so it won't add the `gf_list_2col` CSS class if _any_ `gf_list_*` class is found (@remcotolsma?).

As for the spacing, that is theme territory — we're not adding the additional space in front of the icons from our plugin.

**Comment by remcotolsma** [comment]
> We could maybe change https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/4.0.1/src/PaymentMethodsField.php#L122 to only search for `gf_list_`, so it won't add the `gf_list_2col` CSS class if _any_ `gf_list_*` class is found (@remcotolsma?).

Seems fine to me.
