### ISSUE TITLE
VISA » Update logo to new version

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pronamic-pay#321]
New logo for VISA. It is updated with just one solid color.

![payment-method-visa](https://user-images.githubusercontent.com/610613/168588809-b3157639-b6c4-4cf1-bbda-7ffb9accd52c.svg)

**Comment by remcotolsma** [comment]
More details:

- https://usa.visa.com/about-visa/newsroom/press-releases.releaseId.18156.html
- https://www.businesswire.com/news/home/20210721005260/en/

Our current logo can be found here:

- https://github.com/pronamic/wp-pay-logos/blob/master/src/methods/visa/method-visa-640x360.svg

The official Visa logos can be found here:

- https://www.merchantsignage.visa.com/brand_guidelines

[ab696eb4-ddcf-48ff-8176-da6fa22ae00eVisa_Brandmark_RGB_2021_SVG.zip](https://github.com/pronamic/wp-pronamic-pay/files/8706338/ab696eb4-ddcf-48ff-8176-da6fa22ae00eVisa_Brandmark_RGB_2021_SVG.zip)

**Comment by remcotolsma** [comment]
Added in https://github.com/pronamic/wp-pay-logos/releases/tag/1.8.1.
