### ISSUE TITLE
Gateways / payment methods input fields API 🔁2️⃣

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#336]
- [x] Add support for OmniKassa and AfterPay.nl gender and birthdate field.
- [ ] Remove `IDealIssuerSelectField` class, just use general `SelectField` class?
- [x] Add support for Mollie direct debit and bank account name and IBAN field.
- [ ] Work on unique HTML id and name attributes.

Source: https://github.com/pronamic/wp-pronamic-pay/issues/154#issuecomment-1222428469

**Comment by rvdsteege** [comment]
> Remove IDealIssuerSelectField class, just use general SelectField class?

We might want to do something with last used issuer etc., would a specific `IDealIssuerSelectField` class not make that easier to accomplish (if we are going to map the issuers to a core constant)?

**Comment by remcotolsma** [comment]
Yes, but i don't think it's good practice that it requires a subclass. We could also a `id` or `type` property to identify specific fields:

- ideal_issuer
- gender
- date_of_birth
- etc.

**Comment by remcotolsma** [comment]
For now, we are satisfied with the current implementation.
