### ISSUE TITLE
AfterPay becomes Riverty

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#339]
> **AfterPay** krijgt vanaf 4 oktober een nieuwe naam: **Riverty**. En we nemen jou graag mee op deze spannende reis vol nieuwe mogelijkheden. Lees hier wat blijft, wat nieuw is en wat je nog meer kunt verwachten.
> **Riverty** geeft jou nog meer financiële vrijheid en betalingsoplossingen die passen bij jouw manier van leven. Niet voor niets is onze nieuwe naam geïnspireerd op de vloeiende, natuurlijke stroom van een rivier. Daarmee willen we laten zien dat we volwassen, dynamisch, doelgericht en krachtig zijn, en tegelijkertijd down-to-earth en oprecht. Natuurlijk hoort daar ook een nieuw logo bij.

https://thenext.afterpay.nl/nl

**Comment by remcotolsma** [comment]
Also mentioned in the Pay. newsletter:

> **AfterPay wordt Riverty op 4 oktober 2022**
> Staat 4 oktober al in je agenda? Bij ons wel! AfterPay verandert dan haar naam en logo. Hoe neem je je webshop mee in de verandering?

https://25758250.hs-sites-eu1.com/het-pay.-admin-panel-is-vernieuwd-snelle-en-flexibele-financiering-nodig

> **Zo neem je je webshop mee in de verandering:**
> 
> - Zorg dat je altijd gebruik maakt van de laatste versie van je plugin, zo zorgt Pay. ervoor dat het nieuwe AfterPay-Riverty logo goed wordt weergegeven in je checkout.
> - Maak je gebruik van de betaalpagina van Pay? Zorg dan dat je vanaf 4 oktober alleen de nieuwste versie gebruikt.
> - Plaats vanaf 4 oktober het nieuwe co-branded AfterPay-Riverty logo op je website, bijvoorbeeld in je footer, bij veelgestelde vragen of algemene voorwaarden en verwijs in tekst naar Riverty.
> - Breng jezelf en relevante afdelingen op de hoogte van de [vernieuwde algemene voorwaarden](https://developer.afterpay.io/documentation/compliance-requirements-*new/) van Riverty. Het gaat hier om een naamsverandering - alle contractuele rechten en plichten blijven hetzelfde.

https://www.pay.nl/actueel/afterpay-wordt-op-4-oktober-riverty

**Comment by remcotolsma** [comment]
Apparently AfterPay/Riverty will work with a temporary logo.

![thenext afterpay nl_nl](https://user-images.githubusercontent.com/869674/193012840-ae7212be-664a-4011-a0da-dd47e702e243.png)

**Comment by remcotolsma** [comment]
> **Belangrijk om te weten:**
> 
> - Tot 3 oktober verandert er zichtbaar niets - je blijft het bestaande AfterPay-logo gebruiken op webwinkels, apps en elders.
> - Op 4 oktober start de introductie van de nieuwe naam: Riverty. Op specifieke touchpoints, zoals in de checkout, blijf je het merk AfterPay zien in een gecombineerd logo en als beschrijvende regel onder het nieuwe logo.
> - Vanaf 4 oktober is de naamsverandering doorgevoerd in de betaalplugins van Buckaroo, deze kunnen gedownload en geüpdatet worden via GitHub.

https://www.buckaroo.nl/blog/afterpay-verandert-per-4-oktober-haar-naam-in-riverty

**Comment by remcotolsma** [comment]
- https://github.com/search?q=org%3Apaynl+riverty
- https://github.com/search?q=org%3Abuckaroo-it+riverty
- https://github.com/search?q=org%3AMultiSafepay+riverty

**Comment by remcotolsma** [comment]
I'm not sure this is the official AfterPay/Riverty logo:

https://github.com/buckaroo-it/Media/blob/4ffb6fca1f5f3953f64da8ae15f0303f98ebd7fc/Payment%20methods/SVG/AfterPay.svg

![AfterPay](https://user-images.githubusercontent.com/869674/193014261-ca5c3558-45ab-4eb7-ba49-f50275806abe.svg)

**Comment by rvdsteege** [comment]
> I'm not sure this is the official AfterPay/Riverty logo

Don't think so, it looks different than the one in https://github.com/pronamic/wp-pronamic-pay/issues/339#issuecomment-1262110816...

**Comment by remcotolsma** [comment]
Found some more information on https://getreadyforwhatsnext.afterpay.nl/nl and in https://www.afterpay.nl//uploads/bestanden/merchant-nl/merchant-information-nl-full.pdf.

- https://riverty.design/
- https://getreadyforwhatsnext.afterpay.nl/resources/graphics/logo--riverty.svg
- https://cdn.riverty.design/logo/riverty-checkout-logo.svg

![riverty-checkout-logo](https://user-images.githubusercontent.com/869674/193015057-09d1383d-75cb-4f91-a677-de2d28360328.svg)

![logo--riverty](https://user-images.githubusercontent.com/869674/193015762-e9471486-0f4c-40d4-8788-8bf6f1be797d.svg)

[merchant-information-nl-full.pdf](https://github.com/pronamic/wp-pronamic-pay/files/9674034/merchant-information-nl-full.pdf)

**Comment by remcotolsma** [comment]
This is not a rush / priority for now, I wonder how much AfterPay.nl / Riverty is still being used. Or has AfterPay.nl / Riverty signed their death warrant now that all their customers have to keep up with all the branding changes? ☠️🤡

**Comment by remcotolsma** [comment]
- https://github.com/buckaroo-it/Media/issues/3

**Comment by remcotolsma** [comment]
I have added an extra Riverty gateway in WooCommerce and Easy Digital Downloads.
