### ISSUE TITLE
No iDEAL issuer input field with Pronamic payment method

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#343]
With iDEAL Advanced, the Pronamic payment method used to add the issuer input field at checkout. Since Pronamic Pay version `9.0.0` this is no longer the case. This now results in an error message:

> BIC invalid. Field generating error: issuerID

The `$gateway->payment_method_is_required()` was used to set the payment method to iDEAL in this case:
- https://github.com/pronamic/wp-pay-core/blob/0cdc62c78b59cc71608b0d70abbab3d16f335713/src/Core/Gateway.php#L434-L447

We've removed this method, maybe we can find an other solution to:
1. make this work _or_;
2. prevent the gateway configuration from being used at all if it does not support the Pronamic (`null`) payment method.

**Comment by remcotolsma** [comment]
I think this problem is so small that it has no added value to come up with a solution for this. Most users will now also use the iDEAL gateway within the extensions for the iDEAL payment method.
