### ISSUE TITLE
Add plugin setting to assign `edit_payments` capability to role(s)

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#349]
From customer:

> Misschien handig voor de gewone gebruiker om dit toe te voegen aan de instellingen van de plugin?

> Nu is het zo dat ik de admin-rechten heb en de klant editor-rechten. Ik wil namelijk niet dat een klant complete toegang heeft over bepaalde technische instellingen (`manage_options`) om bijvoorbeeld te voorkomen dat de website niet meer werkt. Dus dan is het wenselijk om de editor toegang te geven aan de payments.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2076968346/24838_

**Comment by remcotolsma** [comment]
For now, we have no plans to add capability/roles management features to the Pronamic Pay plugin. Users who want to deviate from the standard behavior can use an existing user role editor plugin: https://wordpress.org/plugins/search/user+role/.
