### ISSUE TITLE
Regarding cutom fields in gateways

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay#351]
Hello Team

In https://github.com/pronamic/wp-pronamic-pay/issues/154 , you have introduced a way using which we can create custom fields that are required for certain payment methods for a gateway. I have a query regarding the same. There are certain fields for example "Phone Number". Some payment gateway needs a customer phone number field. Some WordPress plugins like Woocommerce by default ask for customer phone number, so this can easily be passed to gateway. But some plugins like EDD, Give etc don't ask for customer phone number by default. If we will create a custom phone number field for that particular payment method/provider, it will ask for phone number again on Woocommerce also. It's not good to ask phone number again when customer has already entered it while filling the checkout form. Where as for EDD and Give, customer needs to enter phone number because this field is missing in these plugins.
Kindly suggest how to proceed with this.

**Comment by rvdsteege** [comment]
We have the same going on with some of our own fields. Please see how we've resolved that in https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/c46f2a96aeb4c48afc91823dc34ea8a0a6f15ab9/src/Gateway.php#L958-L994

Does that answer your question?

**Comment by knit-pay** [comment]
Thanks, will try that and let you know if more help needed.

**Comment by remcotolsma** [comment]
That is indeed a challenge, how do we know which input is provided by plugins such as WooCommerce, Easy Digital Download, Gravity Forms, Contact Form 7, etc. etc.. A WooCommerce telephone number field can also be disabled/removed. And these fields may or may not be mandatory. We do have some specific code in the WooCommerce library for Pronamic Pay for filtering date of birth and gender fields: https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/1af5496b74b23aacc4f48f00f943dda4cfb90c93/src/Gateway.php #L991-L1027. This is not yet very nice, so there is certainly room for improvement. I don't know what the best approach is, I suggest opening a new issue for this.
