### ISSUE TITLE
Reconsider PHP 8 requirement

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#353]
The increased PHP version requirement to `8.0` seems to be causing some issues / frustrations:

> Ik vind dat jullie er wel vrij vroeg bij zijn om PHP8 te eisen. Miljoenen websites draaien daar nog niet op.

> De host geeft aan dat hun systeem nog niet klaar is voor een PHP update.

> On our site, currently the Customizer is broken (it doesn't load). In the error logs I see the followwing:
> 
> ```php
> PHP Fatal error: Uncaught TypeError: Return value of Pronamic\WordPress\Pay\Fields\Field::jsonSerialize() must be an instance of Pronamic\WordPress\Pay\Fields\mixed, array returned in /wp-content/plugins/pronamic-ideal/vendor/wp-pay/core/src/Fields/Field.php:149
> ```

> Recently, the following error message is displayed for the Pronamic plugin
> > This plugin does not work with your version of PHP
> 
> This is the PHP version running on my server: `7.4.33`. Is this PHP version too old to run the plugin?

PHP 7.4 compatibility has already been improved in https://github.com/pronamic/wp-pay-core/commit/b59cc53ae4974de599b4c635651f992173d87007, but maybe we should also reconsider the increased PHP version requirement?

For reference:
- WordPress.org statistics:
  - 56% using PHP `7.4`
  - 15% on PHP `8.0` or higher
  - https://wordpress.org/about/stats/
- WooCommerce 7.3.0 requires PHP version `7.2`
  - https://github.com/woocommerce/woocommerce/blob/2de5a8f08657a70987f48421dc43706890b96e4d/plugins/woocommerce/readme.txt#L6
- Yoast SEO increases the PHP requirement to version `7.2` coming March
  - https://yoast.com/developer-blog/notice-increasing-minimum-php-requirement/
- PHP `7.4` has officially reached 'End of life' and is unsupported
  - https://www.php.net/supported-versions.php

_Internal Help Scout tickets:_
- https://secure.helpscout.net/conversation/2133179817/25099
- https://secure.helpscout.net/conversation/2123834698/25048
- https://secure.helpscout.net/conversation/2128494178/25079
- https://secure.helpscout.net/conversation/2127292448/25074

**Comment by remcotolsma** [comment]
Because almost no PHP 8+ functionalities are used yet, it seems fine to me to continue to support PHP 7.4 for now. I have already modified the libraries, will patch them shortly.
