### ISSUE TITLE
Payment description merge tags

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay#358]
From customer:

> Where can I find a list of available merge tags for WooCommerce, to use in the payment/transaction description?
> 
> […] For the custom payment description I'm now looking for the merge tags for 'single product name' and 'customer name', to make each transaction/payment from WooCommerce more recognizable, both in the Mollie dashboard and in the bank account.
> 
> […] Are there any ready-made merge tags available for this? Or can you help me with a code-snippet to add these in the functions.php of the active theme, to make them available for use in these settings?

We have a few tags available (and mentioned) for use in the WooCommerce payment method description setting: `{order_number}`, `{order_date}`, `{blogname}`.

Specifically for Mollie, there's also a filter `pronamic_pay_mollie_payment_description`:

- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/v4.7.6/docs/hooks.md#pronamic_pay_mollie_payment_description

Custom tag replacements can also be added by hooking into the `pronamic_pay_pre_create_payment` action:

- https://github.com/pronamic/wp-pay-core/blob/v4.9.2/docs/hooks.md#pronamic_pay_pre_create_payment

I've created a Gist for customer and item names tags, using this action:

- https://gist.github.com/rvdsteege/3636b8375e9de5247d14b6dfca77b687

However, we could also add some kind of _merge tag controller_ which allows for payment data being used through tags in the payment description in all supported plugin integrations. For example:

- `{site_title}`
- `{user:name}`
- `{customer:name}`
- `{customer:first_name}`
- `{items}` _payment lines names_
- …

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2239610520/25619_

**Comment by remcotolsma** [comment]
In https://github.com/pronamic/wp-pronamic-pay-adyen/issues/22 a customer also needed the support of merge tags `{gf_form_id}` and `{gf_entry_id}`. If we introduce the ability to register merge tags we could include it in https://github.com/pronamic/wp-pronamic-pay-gravityforms.

**Comment by kjtolsma** [comment]
Ziekenhuis Nij Smellinghe heeft ook de wens om een andere merge tag te gebruiken (Product titel).

**Comment by remcotolsma** [comment]
Ondersteuning voor merge tag `{payment_lines_name}` is toegevoegd via https://github.com/pronamic/wp-pay-core/pull/149. Zojuist ook nog even getest en dit werkt goed:

<img width="1267" alt="Scherm­afbeelding 2023-09-29 om 14 35 48" src="https://github.com/pronamic/wp-pronamic-pay/assets/869674/8d03dcf9-74b3-4049-870d-1829805e2ea8">

<img width="634" alt="Scherm­afbeelding 2023-09-29 om 14 35 25" src="https://github.com/pronamic/wp-pronamic-pay/assets/869674/689f897d-634c-4d78-9432-9d9baed23354">

<img width="1367" alt="Scherm­afbeelding 2023-09-29 om 14 36 29" src="https://github.com/pronamic/wp-pronamic-pay/assets/869674/0fc37945-4c10-431b-a373-40aac5ad4634">

<img width="1373" alt="Scherm­afbeelding 2023-09-29 om 14 36 44" src="https://github.com/pronamic/wp-pronamic-pay/assets/869674/b8283a20-6345-4966-bf73-d3cad637682c">

De nieuwe merge tag functionaliteit geeft ruimte voor meer merge tags, maar voor nu hebben we daar niet hele concrete wensen in.
