### ISSUE TITLE
Add bank images and options to show issuer list with radiobuttons

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#5]

**Comment by rvdsteege** [comment]
Issuer list with images is supported in some of the extensions (e.g. Gravity Forms, WooCommerce).

Should we close this issue, @remcotolsma?

**Comment by remcotolsma** [comment]
I still had some ideas regarding the display of the iDEAL banks choice, sometimes I come across nice alternative views at Dutch webshops.

## Gravity Forms

### List with icons

![pay local__gf_page=preview id=1](https://user-images.githubusercontent.com/869674/122213116-e4991f80-cea8-11eb-9a18-ba72717fe1c5.png)

### Small icons

![pay local__gf_page=preview id=1 (1)](https://user-images.githubusercontent.com/869674/122213200-00042a80-cea9-11eb-9101-ad1b9bcb4b1c.png)

### Large icons

![pay local__gf_page=preview id=1 (2)](https://user-images.githubusercontent.com/869674/122213278-13af9100-cea9-11eb-8818-6cb6939fa59f.png)

_I noticed that the small icons are quite large compared to the large icons._

https://github.com/wp-pay-extensions/gravityforms/blob/e8329f1cc6b0541b376c35566ce5194ee0a18399/src/Fields.php#L134-L136

Maybe rename 'small icons' to 'icons only' and the 'large icons' to 'full logo'?

## Idea

Sometimes i also see a combination of a `<select>` element with all the logos of the iDEAL banks underneath. When clicking on the logo of a bank, the bank in the `<select>` element is automatically selected.

Maybe one day we can launch components for the iDEAL bank choice including all HTML, CSS and JavaScript, similar to:

- https://developer.wordpress.org/block-editor/reference-guides/components/dropdown-menu/
- https://getbootstrap.com/docs/5.0/components/dropdowns/
- https://material-ui.com/components/selects/

We already have a nice bank card component:

![pay local__subscription=246 key=subscr_609922ad00b29 action=mandate (1)](https://user-images.githubusercontent.com/869674/122216225-6dfe2100-ceac-11eb-9758-4e47c8c8657e.png)

https://github.com/wp-pay/core/blob/2.7.0/scss/card-slider.scss

It would be cool if other developers could use such components easily(er).

## iDEAL Merchant Integration Guide

_Version 3.3.1 (november 2012)_

> **4.4 Presentation of the Issuer selection list**
> 
> To ensure that the Consumer experience of an iDEAL transaction is consistent and recognizable
> through all Merchant websites; all Merchants have to comply with certain presentation standards.
> 
> All Issuers in the DirectoryResponse have to be shown in a “dropdown list box”. The first element
> in this list is “Kies uw bank…” (_Eng. “Choose your bank…”_), and is selected by default.
> Subesequently the name of the Merchant’s country of choice is shown (either the Merchant’s own
> country or the country the Consumer is (expected to be) from). The names of all Issuers that
> belong to the Merchant’s country of choice are presented next in separate elements, in the same
> (alphabetical) order as they are presented in the DirectoryResponse. Following this the names of
> other available countries are presented alphabetically, within each country the banks from are
> sorted alphabetically, in the same order as presented in the DirectoryResponse. The Merchant
> should generate an error message whenever one of the elements “Kies uw bank…” and
> countryNames elements is selected by the Consumer.
> 
> _² Country names need only be displayed if there are banks from more than one country on the Issuer list. If all banks in
> the list are from the same country, the country name can be omitted._
> 
> It is recommended to configure the HTML “value” field of the items in the list box to be the
> issuerID (BIC) of the corresponding Issuer, because this value is necessary for subsequent
> messages.
> An example of the Issuer selection list is shown in Figure 3.
> 
> ![ideal-issuer-select](https://user-images.githubusercontent.com/869674/122209387-c2050780-cea4-11eb-8843-86113022edf2.png)
> 
> **Figure 3: Example of (open) dropdown list box showing the Issuer list.**
> 
> Merchants are not permitted to remove Issuing banks temporarily from the Issuer selection list or
> to grey them out.
> 
> If a Merchant learns via the iDEAL Notification System (Central Reporting tool for iDEAL banks to
> state system non-availability) or via error messages received from the Acquiring bank that a
> particular Issuing bank is not currently available, the Merchant may display a message on its
> website informing Consumers that the particular bank is not available. In other words, it is
> perfectly permissible to display a message conveying such information but it is not permissible to
> temporarily remove or grey out the Issuing bank concerned from the Issuer selection list.

_Source:_ https://www.pronamic.nl/wp-content/uploads/2012/12/iDEAL-Merchant-Integration-Guide-ENG-v3.3.1.pdf

## Other Examples

![2020-12-02-16_26_56-HPP](https://user-images.githubusercontent.com/869674/122212168-d565a200-cea7-11eb-8d10-24db2e9a43d9.png)

![ideal_voorbeeld_1](https://user-images.githubusercontent.com/869674/122212219-e1e9fa80-cea7-11eb-8e6e-107b74041553.png)

![ideal-ticketsysteem](https://user-images.githubusercontent.com/869674/122212240-e6161800-cea7-11eb-9c85-69fecd41019f.png)

![09-iDEAL-Betaalverzoek_291042533](https://user-images.githubusercontent.com/869674/122212260-ec0bf900-cea7-11eb-8d7f-c87a5c7d0db5.jpeg)

![Online-betalen-5](https://user-images.githubusercontent.com/869674/122212280-f201da00-cea7-11eb-9d37-8bec9dd4c963.png)

**Comment by rvdsteege** [comment]
From customer:

> Is het mogelijk om logo's van banken te tonen bij de selectie van betalen met iDeal? Nu staan alleen de namen er, maar voor de herkenning en snelheid van de flow lijkt het ons handig om ook de logo's te tonen. Of hebben jullie dit bewust niet gedaan?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2063979297/24776_

**Comment by remcotolsma** [comment]
With iDEAL 2 the bank choice on the website side will disappear, I am therefore closing this issue.
