### ISSUE TITLE
Let visitors pay later

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#8]

**Comment by rvdsteege** [comment]
@remcotolsma We support the AfterPay payment method and others for this. Close this issue?

**Comment by remcotolsma** [comment]
This was intended differently, for example for visitors who fill out a Gravity Forms payment form, but do not have their mobile phone and banking app at hand at that time. But since this hasn't been a problem for the past few months, we're closing this issue for now.
